### ISSUE TITLE
atomWithMachine: fast refresh state update issue

### ISSUE THREAD

**Issue by bstro** [pmndrs/jotai#1278] opened 2022-07-13 22:08 UTC
Creating a proper issue for this fast refresh bug. I originally posted in https://github.com/pmndrs/jotai/issues/1150 but it ended up being unrelated.

Expected: values managed by Jotai's `atomWithMachine` should not be lost between fast-refresh UI updates.

Actual: `atomWithMachine` state resets upon fast refresh update.

Stackblitz: https://stackblitz.com/edit/vitejs-vite-xgnuvc?file=src%2FApp.tsx

Instructions:
Click the `inc` button to increment the counter
Edit the text inside `App` component. The counter will be reset back to 0.

**Comment by dai-shi** [comment] 2022-07-14 00:03
Thanks for opening an issue.

Sad to tell, but this is simply not supported yet. We don't even know how.

Here's a smaller reproduction without `atomWithMachine`.

```js
const createMachineLikeAtom = () => {
  const baseAtom = atom({ context: { count: 0 } });
  const derivedAtom = atom(
    (get) => get(baseAtom),
    (get, set, evt) => {
      const count = get(baseAtom).context.count;
      if (evt === 'INC') {
        set(baseAtom, { context: { count: count + 1 } });
      }
      if (evt === 'DEC') {
        set(baseAtom, { context: { count: count - 1 } });
      }
    }
  );
  return derivedAtom;
};

const machineAtom = createMachineLikeAtom();
```

https://stackblitz.com/edit/vitejs-vite-gcfatg?file=src%2FApp.tsx

cc @Thisen

**Comment by dai-shi** [comment] 2022-07-14 00:06
Hm, but we can cache `atomWithMachine()` entirely, like `atom()`. So, it's easier than the smaller reproduction...

What do you think? @Thisen

**Comment by Thisen** [comment] 2022-07-14 06:27
> Hm, but we can cache `atomWithMachine()` entirely, like `atom()`. So, it's easier than the smaller reproduction...
> 
> What do you think? @Thisen

We can just cache it. Opening a PR.

**Comment by dai-shi** [comment] 2022-07-14 08:56
(I think I assumed too much difficult.)

**Comment by bstro** [comment] 2022-07-15 17:45
https://stackblitz.com/edit/vitejs-vite-w2pxp7?file=src%2FApp.tsx&terminal=dev

I'm still seeing the issue after upgrading to `1.7.5`.

**Comment by Thisen** [comment] 2022-07-20 06:57
> The insanely fast turnaround is very much appreciated! <3
> 
> Still seeing the problem:
> 
> https://stackblitz.com/edit/vitejs-vite-w2pxp7?file=src%2FApp.tsx&terminal=dev
> 
> I'm still seeing the issue after upgrading jotai to `1.7.5`.

Your reproduction is not using the react-refresh Babel plugin.

**Comment by Thisen** [comment] 2022-07-21 07:56
Closing. Feel free to re-open if you still experience issues :)

**Closed by Thisen** 2022-07-21 07:56 UTC
Labels: enhancement

**Comment by bstro** [comment] 2022-07-21 18:57
Ahhh whoops. My apologies. Thank you for your assistance!

**Comment by dlindahl** [comment] 2022-11-09 00:13
I'm still experiencing issues with this on `jotai` v1.9.1, `xstate` 4.34.0, and `@xstate/react` 3.0.1.

I have two atoms that store state through an xstate machine. One of those atoms is in a context that uses `// @refresh reset`. In this context, when HMR kicks in, the atom is [unmounted, remounted](https://github.com/pmndrs/jotai/blob/225d719630c07cb5601e0805a4b5fc8f1b2d7a3e/src/xstate/atomWithMachine.ts#L139-L156), and the underlying [service is restarted](https://github.com/pmndrs/jotai/blob/225d719630c07cb5601e0805a4b5fc8f1b2d7a3e/src/xstate/atomWithMachine.ts#L131).

In the other context that lacks `// @refresh reset`, when HMR kicks in, the atom does _not_ unmount and remount and the service remains stuck, `send` events do not do anything. I can call `can`, I can look at `nextEvents` which are both accurate. But calling `send` is a no-op. I stepped through the entire workflow from my call to `send` and through `jotai` and into `xstate` and found that while the [`this.status`](https://github.com/statelyai/xstate/blob/5e0808eb440f77b8404db6676401849053cfcfd8/packages/core/src/interpreter.ts#L710) is `0`, and the code runs through as expected, the [`this.scheduler.schedule` function](https://github.com/statelyai/xstate/blob/5e0808eb440f77b8404db6676401849053cfcfd8/packages/core/src/interpreter.ts#L739-L746) never runs the queued function that is necessary for the queued event to propagate through the machine. It almost feels as if the machine "forgets" that it has been started.

If I update this other atom context to include `// @refresh fast`, the atom will unmount, remount, and the machine works as expected, but I imagine that having to use that is not the intended or desired workflow and that `atomWithMachine` should Just Work ™️  without it, but its not clear...

**Comment by Thisen** [comment] 2022-11-09 07:43
> I'm still experiencing issues with this on `jotai` v1.9.1, `xstate` 4.34.0, and `@xstate/react` 3.0.1.
> 
> I have two atoms that store state through an xstate machine. One of those atoms is in a context that uses `// @refresh reset`. In this context, when HMR kicks in, the atom is [unmounted, remounted](https://github.com/pmndrs/jotai/blob/225d719630c07cb5601e0805a4b5fc8f1b2d7a3e/src/xstate/atomWithMachine.ts#L139-L156), and the underlying [service is restarted](https://github.com/pmndrs/jotai/blob/225d719630c07cb5601e0805a4b5fc8f1b2d7a3e/src/xstate/atomWithMachine.ts#L131).
> 
> In the other context that lacks `// @refresh reset`, when HMR kicks in, the atom does _not_ unmount and remount and the service remains stuck, `send` events do not do anything. I can call `can`, I can look at `nextEvents` which are both accurate. But calling `send` is a no-op. I stepped through the entire workflow from my call to `send` and through `jotai` and into `xstate` and found that while the [`this.status`](https://github.com/statelyai/xstate/blob/5e0808eb440f77b8404db6676401849053cfcfd8/packages/core/src/interpreter.ts#L710) is `0`, and the code runs through as expected, the [`this.scheduler.schedule` function](https://github.com/statelyai/xstate/blob/5e0808eb440f77b8404db6676401849053cfcfd8/packages/core/src/interpreter.ts#L739-L746) never runs the queued function that is necessary for the queued event to propagate through the machine. It almost feels as if the machine "forgets" that it has been started.
> 
> If I update this other atom context to include `// @refresh fast`, the atom will unmount, remount, and the machine works as expected, but I imagine that having to use that is not the intended or desired workflow and that `atomWithMachine` should Just Work ™️ without it, but its not clear...

Could you create a reproduction?
