### ISSUE TITLE
`useAtom` has something wrong when dynamic return an `atom`

### ISSUE THREAD

**Issue by SquirrelJimmy** [pmndrs/jotai#897] opened 2021-12-17 08:29 UTC
Example:
```ts
import { atom } from 'jotai';
import { atomWithStorage, createJSONStorage } from 'jotai/utils';


export const isComparison = atomWithStorage('isComparison', false, createJSONStorage(() => sessionStorage) as any);

export const test = atom((get) => {
  const re = get(isComparison);
  const date = re ? new Date() : null;  
  return date;
})
```
atomWithStorage:
```ts
export function atomWithStorage<Value>(
  key: string,
  initialValue: Value,
  storage:
    | SyncStorage<Value>
    | AsyncStorage<Value> = defaultStorage as SyncStorage<Value>
) {
 //...
  const baseAtom = atom(storage.delayInit ? initialValue : getInitialValue())

  baseAtom.onMount = (setAtom) => {
    let unsub: Unsubscribe | undefined
    if (storage.subscribe) {
      unsub = storage.subscribe(key, setAtom)
    }
    if (storage.delayInit) {
      const value = getInitialValue()
      if (value instanceof Promise) {
        value.then(setAtom)
      } else {
        setAtom(value)
      }
    }
    return unsub
  }

  const anAtom = atom(
    (get) => get(baseAtom),
    (get, set, update: SetStateAction<Value>) => {
      const newValue =
        typeof update === 'function'
          ? (update as (prev: Value) => Value)(get(baseAtom))
          : update
      set(baseAtom, newValue)
      return storage.setItem(key, newValue)
    }
  )
// new atom;
  return anAtom
}
```
when `useEffect`:
```ts
 const [res] = useAtom(test);
  const [, setIsComparison] = useAtom(isComparison)
  useEffect(() => {
    setIsComparison(true);
  }, [setIsComparison])  
```
something goes wrong:
![image](https://user-images.githubusercontent.com/24666536/146513402-3a58921e-d8b2-4c05-a9c3-fcca7614a6b2.png)
infinity update!

at `useAtom`: 
```ts
useEffect(() => {
  store[COMMIT_ATOM](atom)
})
// It's missing dep array
useEffect(() => {
  store[COMMIT_ATOM](atom)
}, [store, atom])
```

**Comment by dai-shi** [comment] 2021-12-17 09:10
As far as I remember, the implementation was intentional, but infinite loop is something we should fix. Can you create a **minimal** test case?

**Comment by SquirrelJimmy** [comment] 2021-12-17 10:28
> As far as I remember, the implementation was intentional, but infinite loop is something we should fix. Can you create a **minimal** test case?

click this: https://codesandbox.io/s/pensive-joliot-sm324

**Comment by SquirrelJimmy** [comment] 2021-12-17 10:30
> As far as I remember, the implementation was intentional, but infinite loop is something we should fix. Can you create a **minimal** test case?

under `1.4.4` have no problem

**Comment by dai-shi** [comment] 2021-12-17 11:40
> under `1.4.4` have no problem

Cool. So, it's likely #841 causing this.

Would you like to keep investigating on it? (otherwise, @Thisen might be interested working on it.)

**Comment by dai-shi** [comment] 2021-12-17 12:02
Okay... I just encountered this issue while I'm working on [katachidraw](https://github.com/dai-shi/katachidraw) and updating jotai. 😱 Yeah, it's a fatal bug.

**Comment by dai-shi** [comment] 2021-12-17 13:02
@Thisen Feel free to work on it as this is such an unexpected regression. If nobody starts working on this, I will.

**Comment by SquirrelJimmy** [comment] 2021-12-20 04:44
> Okay... I just encountered this issue while I'm working on [katachidraw](https://github.com/dai-shi/katachidraw) and updating jotai. 😱 Yeah, it's a fatal bug.
```ts
const [[value, atomFromUseReducer], forceUpdate] = useReducer(
    useCallback(
      (prev) => {
        const nextValue = getAtomValue()
        // It's terrible, if atom return object value ,Object.is always returns true, here need deepEquel
        if (Object.is(prev[0], nextValue) && prev[1] === atom) {
          return prev // bail out
        }
        return [nextValue, atom]
      },
      [getAtomValue, atom]
    ),
    undefined,
    () => {
      const initialValue = getAtomValue()
      return [initialValue, atom]
    }
  )
```
`Object.is` is terrible

**Comment by dai-shi** [comment] 2021-12-20 04:55
No, it's just emulating the default useReducer behavior (they use react.is or something). This is not the source of the problem. We never use deep equal.

**Comment by SquirrelJimmy** [comment] 2021-12-20 05:10
> No, it's just emulating the default useReducer behavior (they use react.is or something). This is not the source of the problem. We never use deep equal.

if verson is greater than `1.4.4`
```ts
const depAtom = atom(/**some value*/false);
const anOtherAtom = atom((get) => {
   const dep = get(depAtom);
   return {
    dep
  }
});

// Views

function UI () {
  const [,setDep] = useAtom(depAtom)
  const [value] = useAtom(anOtherAtom)
  useEffect(() => {setDep(true)}, []);
return /**something*/
}
```

**Comment by dai-shi** [comment] 2021-12-20 07:11
> must be replay

Oh, cool. Let me create a test with this. @Thisen might have already worked on it, but this is such an important issue, so both of us can work on it.

https://github.com/pmndrs/jotai/blob/4721203bc0a1b2a8c53f0b41e5569740ee392fc5/src/core/useAtom.ts#L76

I'm pretty sure this `forceUpdate()` is causing the issue. If we don't find a solution, we could technically revert #841 (meaning comment this line out).

@SquirrelJimmy Thanks tons for your investigation!

**Comment by dai-shi** [comment] 2021-12-20 07:51
```ts
it('derive with a new object (#897)', async () => {
  const countAtom = atom(0)
  const derivedAtom = atom((get) => ({
    count: get(countAtom),
  }))

  const Counter = () => {
    const [, setCount] = useAtom(countAtom)
    const [{ count }] = useAtom(derivedAtom)
    useEffect(() => {
      setCount((c) => c + 1)
    }, [setCount])
    return <div>count: {count}</div>
  }

  const { findByText } = render(
    <Provider>
      <Counter />
    </Provider>
  )

  await findByText('count: 1')
})
```

Hmmm, this doesn't fail in tests. Is this issue specific to CJS build? 🤔

**Comment by dai-shi** [comment] 2021-12-20 09:10
https://codesandbox.io/s/sharp-star-l2y15?file=/src/App.js
Ah, this doesn't repro either. We are missing something else.

**Comment by dai-shi** [comment] 2021-12-20 09:32
Okay, this is more complicated than my expectation. Commenting out `forceUpdate` doesn't fix.
Just committed the failing test in #900.

**Comment by dai-shi** [comment] 2021-12-20 09:35
Interesting enough, the test passes on React 16.8.6. (maybe with some bugs?)

<img width="492" alt="image" src="https://user-images.githubusercontent.com/490574/146745319-47772b7e-5100-4573-957a-3d147db73d1b.png">

**Comment by dai-shi** [comment] 2021-12-20 09:58
Oh, I misunderstood something completely. jotai v1.4.6 has no issues, and v1.4.7 has the issue. So, this is due to my refactors. I'll work on it.

**Closed** 2021-12-20 11:03 UTC
Labels: bug

**Comment by Ynewtime** [comment] 2021-12-20 12:15
Hi @SquirrelJimmy have your issue been resolved? 

After upgrading to 1.4.7 I falled into the same rabit hole and fix the version in 1.4.4 to resolve it. I wanna share a reproduction but cannot since my project is inside of my company and I cannot figure out a way to reproduce it neigther since the project is quite a large codebase.

I am happy to see 1.4.9 been released and head to try it but it gets worse. Previous the 'Maximum update' happened if I changed some states but now it happens once I open the page. So I revert to 1.4.4 again.

Will try to figure out a way to reproduce my 'Maximum update' issue.

**Comment by dai-shi** [comment] 2021-12-20 12:46
> Will try to figure out a way to reproduce my 'Maximum update' issue.

Oh, no... It would be so nice if you find a way to reproduce the issue.

**Comment by dai-shi** [comment] 2021-12-20 12:52
@Ynewtime Just a quick confirmation. Does v1.4.6 work without any issues?

**Comment by Ynewtime** [comment] 2021-12-20 14:08
> @Ynewtime Just a quick confirmation. Does v1.4.6 work without any issues?

Emm... no. When I upgraded to 1.4.7, the 'Maximum update' bug happened and I checked the recent release of Jotai, couldn't find out the reason behind the issue so I tried revert to 1.4.6, then 1.4.5 and then 1.4.4 fix the issue.

> Oh, no... It would be so nice if you find a way to reproduce the issue.

I think my issue is related with `selectAtom`, here is the reproduction link:

https://codesandbox.io/s/amazing-brook-bxr8i?file=/src/App.js

**Comment by dai-shi** [comment] 2021-12-21 03:05
@Ynewtime Thanks for the reproduction.

1.4.5 has #841, so it's causing this behavior.

As I look your codesandbox, the reason of the behavior is unstable selector function.
We need to wrap it with `useCallback`.
https://codesandbox.io/s/epic-glitter-5ji99?file=/src/App.js:251-298

I didn't know 1.4.4 works without useCallback, but it's never intended. #841 fixes #827 and it reveals the changing atom behavior. Sorry for the inconvenience, but this is how it works now.

**Comment by dai-shi** [comment] 2021-12-21 03:17
btw, useCallback works for selectAtom, but we generally recommend useMemo to create an atom in render. it's not for any technical reason, but for a practice.

```js
  const countAtom = useMemo(() => selectAtom(
    wrappedAtom,
    (state) => state[type]
  ), [type])
```

**Comment by Ynewtime** [comment] 2021-12-21 08:16
> the reason of the behavior is unstable selector function

Thanks for the info, now it's clear.

> Sorry for the inconvenience, but this is how it works now.

Totally understand, will refactor with useCallback. Thanks. BTW, maybe it's better to put this info in the doc or somewhere in the error message, which will be much easier for us to debug this kind of issue.

> but we generally recommend useMemo to create an atom in render

One more best practice got, will try.

**Comment by dai-shi** [comment] 2021-12-21 10:00
> BTW, maybe it's better to put this info in the doc or somewhere in the error message, which will be much easier for us to debug this kind of issue.

totally. we need to improve docs. let me file an issue for this specific note. 👉 #904
