### ISSUE TITLE
[Regression Bug] Unexpected LocalStorage access breaks Next.js at build time

### ISSUE THREAD

**Issue by xbaun-mms** [pmndrs/jotai#967] opened 2022-01-15 13:59 UTC
The `createJSONStorage` factory function shouldn't access the LocalStorage without explicitly being called. Next.js breaks when building because LocalStorage is not available at build time or in SSR mode.

https://github.com/pmndrs/jotai/blob/db3efa5c043b83d16ade5a7b351952be364605b0/src/utils/atomWithStorage.ts#L58

https://github.com/pmndrs/jotai/blob/db3efa5c043b83d16ade5a7b351952be364605b0/src/utils/atomWithStorage.ts#L77

Affects version 1.5.1 and above.

**Comment by dai-shi** [comment] 2022-01-15 14:01
Should be handled in #951?

**Comment by xbaun** [comment] 2022-01-15 14:04
Sorry, didn't see the issue. This issue can be closed as it is a duplicate of #951.

**Comment by dai-shi** [comment] 2022-01-15 14:08
#951 is already merged and released: https://github.com/pmndrs/jotai/releases/tag/v1.5.2

**Closed by dai-shi** 2022-01-15 14:08 UTC
