### ISSUE TITLE
jotai/urql client getter get a wrong atom value

### ISSUE THREAD

**Issue by kalvin807** [pmndrs/jotai#622] opened 2021-07-30 02:47 UTC
Hi, I am trying to use jotai to manage the state of an app with a login system. When a user login, app will receive a token and the app will use it to create an urql client with the token as the bearer key.

However, the app will crash whenever the login state change like this: `login -> logout -> login (crash!)`, and saying `Cannot read property 'query' of null` . It looks like the getter in atomWithQuery somehow fetched an old value, but when I try to log the client they get, it all look fine (showing a client object). I wonder if I missed something, or it is a bug.

A small demo to the problem, the app will crash when you attempt to login the second time: [Link](https://codesandbox.io/s/test-jotai-urql-crash-3mi3y?file=/src/App.js)  
Stack-trace
```
TypeError
Cannot read property 'query' of null
Object.eval [as read]
https://codesandbox.io/static/js/sandbox.68fd4509e.js:1:100695
readAtomState
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:258:33
eval
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:261:25
Object.eval [as read]
https://codesandbox.io/static/js/sandbox.68fd4509e.js:1:100695
readAtomState
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:258:33
eval
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:241:13
readAtomState
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:237:19
readAtom
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:319:21
eval
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:643:23
checkForUpdates
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:69:30
eval
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:521:63
eval
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:521:43
flushPending
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:511:11
eval
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:406:5
Object.config.write
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:632:7
writeAtomState
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:384:30
writeAtom
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:417:3
updateAtom
https://3mi3y.csb.app/node_modules/jotai/esm/index.js:562:40
eval
https://codesandbox.io/static/js/sandbox.68fd4509e.js:1:100695
eval
/src/App.js:59:4
  56 | const [token, setToken] = useState(null);
  57 | 
  58 | useEffect(() => {
> 59 |   setClient(generateClient(token));
     |  ^
  60 | }, [token]);
  61 | 
  62 | return (
View compiled
▶ 12 stack frames were collapsed.
```

**Comment by dai-shi** [comment] 2021-07-30 04:34
Hi, thanks for reporting.
Your way of safe guard seems good and I'd probably do the same.
So, in this sense, this is a bug. `fetch null` shouldn't be logged.

I'm not sure if this is easily solvable, or requires a different route (like adding the guard in atomWithQuery as a last resort).

If someone wants to tackle this issue, they are welcomed. Just drop a note.

Meanwhile, I got a workaround. This is a bit hacky and not recommended for a long term (at this point).
https://codesandbox.io/s/test-jotai-urql-crash-forked-i4bj5

**Comment by dai-shi** [comment] 2021-07-31 02:42
This may require a fix in code, in such case, I would appreciate for a core-only test.

**Comment by israelidanny** [comment] 2021-08-02 18:27
Right now `getClient` doesn't support getting null at all. What behavior do we want to resort to if `getClient` returns null as far as the atom itself?

**Comment by israelidanny** [comment] 2021-08-02 21:42
Reading through urql's own documentation it seems like they recommend to have a client for both authenticated and non-authenticated states:
https://formidable.com/open-source/urql/docs/advanced/authentication/#cache-invalidation-on-logout

The more I think about it , the more it seems to me that a null client is an anti-pattern.

**Comment by dai-shi** [comment] 2021-08-02 22:29
Thanks for the investigation!

> What behavior do we want to resort to if `getClient` returns null as far as the atom itself?

From jotai perspective, the atom should suspend (= throw a promise).

> Reading through urql's own documentation it seems like they recommend to have a client for both authenticated and non-authenticated states:

Well then, this seems like a doc issue?

**Comment by israelidanny** [comment] 2021-08-02 22:38
For what it is worth, the urql official provider wouldn't accept a null value for client, so it definitely seems like an edge case to be avoided and/or taken care of via guards that prevent even the use of such an atom if no client would exist.

Definitely seems like a documentation issue IMHO

**Comment by dai-shi** [comment] 2021-08-02 22:52
https://codesandbox.io/s/test-jotai-urql-crash-3mi3y?file=/src/App.js
The way it guards against null client seems reasonable.
So, there's probably a timing issue in jotai core (or in jotai/urql), which may or may not be fixable.
If it's not fixable, we should provide a better workaround for such guard.

**Comment by israelidanny** [comment] 2021-08-02 22:54
I added a few tests for the usecase that *is* supported by types right now. The tests are passing. I thought it's an important step (to not break the already working functionality if we want to catch the timing issue), it's also good to have tests for this as this is a common use case (re-initializing client based on authentication for example, like in my use case):
https://github.com/pmndrs/jotai/pull/634

**Comment by israelidanny** [comment] 2021-08-02 23:59
> > What behavior do we want to resort to if `getClient` returns null as far as the atom itself?
> 
> From jotai perspective, the atom should suspend (= throw a promise).

How do we throw a promise which we don't know the resolve time for? Wouldn't that just suspend the component indefinitely? (without resorting to polling)

**Comment by dai-shi** [comment] 2021-08-03 00:15
https://codesandbox.io/s/test-jotai-urql-crash-forked-i4bj5
well, with this hack, it throw an infinite promise. (there's a trick in jotai core to make this work.)

**Comment by israelidanny** [comment] 2021-08-03 00:47
<img width="1189" alt="Screen Shot 2021-08-03 at 03 45 38" src="https://user-images.githubusercontent.com/1970424/127940588-fa1fe61a-2334-4f60-bdac-64dd79bddd62.png">
In this example we never end up throwing that infinite promise. (note that nowhere does it say "fetch null")
I confirmed that whenever we do, we end up suspending render infinitely.

**Comment by israelidanny** [comment] 2021-08-03 01:12
Added this behavior here:
https://github.com/pmndrs/jotai/pull/635

**Comment by dai-shi** [comment] 2021-08-03 03:11
I'm not confident if that's the right approach. I doubt it.
Let me merge #634 first.

**Comment by israelidanny** [comment] 2021-08-03 09:16
> I'm not confident if that's the right approach. I doubt it.
> Let me merge #634 first.

I anticipated this :) Wasn't sure about this myself, hence why I created https://github.com/pmndrs/jotai/pull/634

What's left, then is to create a failing test in core for this bug and try to hunt it. I can extract a failing test & create a PR that anyone can pick up & debug, to help this move along, although personally I don't have any utility for a client null situation.

**Comment by dai-shi** [comment] 2021-08-03 09:51
If you can create a failing test in core, it will help A LOT and I can take it over.

**Comment by israelidanny** [comment] 2021-08-03 10:01
@dai-shi does this help as a starting point?
https://github.com/pmndrs/jotai/pull/636

**Comment by dai-shi** [comment] 2021-08-03 11:09
Thanks for the starting point. What I would like to know is whether this issue is coming from `jotai/urql` or `jotai` itself. My guess is it's jotai itself. If it's the case, we want a test case without `jotai/urql`.

**Comment by israelidanny** [comment] 2021-08-03 11:11
Understood. It would be significantly harder to produce a test case without
urql because it would require some debugging time. I don’t have any
resources towards this specific debugging task because it has no utility in
any of my use cases and also the urql standard way does not recommend to
use “null”.

Realistically, It’ll take me a few weeks to get to there. So if any other
contributor wants to take a stab until then, they can look at the PR I
created & use it as a starting point.

**Comment by dai-shi** [comment] 2021-08-03 11:34
Makes sense. Thanks for your help.
Let's see if someone has some interests in this. cc @Thisen

**Comment by Thisen** [comment] 2021-08-16 19:00
Alright, I've looked into it.

From my side, it looks like Jotai core is behaving like expected. I've used #636 as my reference point. What happens is that the `set` function of the `clientAtom` is called and set to `null`, which triggers the dependent `queryAtom`. However `queryAtom` expects the client to not be `null`, which breaks it.

I've made a CSB that simulates the behavior/relationship between clientAtom/atomWithQuery here:
https://codesandbox.io/s/jotai-issue-622-0cqgh?file=/src/App.js

After looking into `urql` docs, it looks like, as @israelidanny mentioned, that it looks like a null client is an anti-pattern and it doesn't look like it's accepted by the types of `urql` aswell.

CC: @dai-shi

**Comment by dai-shi** [comment] 2021-08-16 23:39
@Thisen Thanks for your investigation.

https://codesandbox.io/s/jotai-issue-622-forked-hozq0
This adds `guardedHelloAtom`, and the error is gone.
I wonder what would be the difference between this and #636.

---

> it looks like a null client is an anti-pattern and it doesn't look like it's accepted by the types of `urql` aswell.

Yes, it's an anti-pattern. The canonical fix for `jotai/urql` will be #649.
However, I expected the guard should work. #636 seems valid in JavaScript. Or, I miss something.

**Comment by Thisen** [comment] 2021-08-17 09:11
> I wonder what would be the difference between this and #636.

Me too - I don't see a clear difference.

**Comment by israelidanny** [comment] 2021-08-19 08:56
#636 still feels like a race condition to me because conceptually there shouldn't be any issue. Could we be dealing with a peculiarity of how React batches the hook execution rather than Jotai core itself?

**Comment by dai-shi** [comment] 2021-08-19 10:49
Yeah, I hope it works. I think we should at least know how this is happening.
I still wonder the difference between https://codesandbox.io/s/jotai-issue-622-forked-hozq0 and #636.

I will dig into it when I get time but feel free to try if you are interested.

**Comment by Aslemammad** [comment] 2021-09-25 11:56
Hey folks! Sorry for the late response 😅
The issue is solved with the magical solution (that wasn't intended to solve this issue) by @Pinpickle in jotai#v1.3.4.

`Cannot read property of 'query' of null` for [`client`](https://github.com/pmndrs/jotai/blob/main/src/urql/atomWithQuery.ts#L95) is present as it was before v1.3.4, however, this time, when it occurs, [L195](https://github.com/pmndrs/jotai/blob/main/src/core/store.ts#L195) is going to handle (delete) it & retries again, in the next try, [`client`](https://github.com/pmndrs/jotai/blob/main/src/urql/atomWithQuery.ts#L95) is going to be defined, so no error in that try!

**Comment by dai-shi** [comment] 2021-09-25 12:17
Oh!! Very nice finding!!!

So, it was the fundamental issue with async atoms.

> What I would like to know is whether this issue is coming from jotai/urql or jotai itself. My guess is it's jotai itself.

Now, I know, my guess was right. What a relief.

@Aslemammad Great work you did, even if the fix is from another PR. I appreciate it so much.
While you are at it, would you update #636 (you should have a grant) to merge the main branch and see if the CI passes?

**Comment by Aslemammad** [comment] 2021-09-25 13:28
@dai-shi Thanks! I'll pull it & send a new PR soon! Thanks @israelidanny

**Comment by dai-shi** [comment] 2021-09-25 23:39
#733 is merged. Nice work, everyone.

**Closed by dai-shi** 2021-09-25 23:39 UTC
