### ISSUE TITLE
Problems with React Fast Refresh

### ISSUE THREAD

**Issue by StarpTech** [pmndrs/jotai#1025] opened 2022-02-22 19:02 UTC
Hi, while it works well in most cases, we experience some bugs.

1. Editing functions out of react tree aren't updated. For example, update the logic of your read-only atom and issue a state update.
2. The referential integrity of the atom store gets broken. I receive no longer state updates. I need to reload to fix it.

All issues happen when using react fast refresh with https://github.com/gsoft-inc/craco. We use the jotai babel preset as documented on the website!

Thank you and keep up the good work!

**Comment by dai-shi** [comment] 2022-02-23 00:48
Hi, can you reproduce some of concrete examples in codesandbox?
(Then, @Thisen can investigate it?)

**Comment by Thisen** [comment] 2022-02-23 07:39
> Hi, can you reproduce some of concrete examples in codesandbox? (Then, @Thisen can investigate it?)

Yes, I'll look into it, when there's a reproduction 👍🏼

**Comment by StarpTech** [comment] 2022-02-23 09:06
Yes, I'll try.

**Comment by StarpTech** [comment] 2022-02-23 10:37
Hi, this is not my main issue but it could be related. Shouldn't the state be preserved when updating the read function?

- https://codesandbox.io/s/nextjs-with-jotai-async-forked-w70o06?file=/store.js (line 30)

**Comment by StarpTech** [comment] 2022-02-25 18:02
@Thisen friendly ping

**Comment by Thisen** [comment] 2022-02-27 13:53
After I looked at it, I'd expect your scenarios to break, given the somewhat simple implementation of our React refresh integration. 

The question is if we are willing to solve it. If so, we need to either re-implement the solution or find some smart way to clean up the `Map`, when the atom function changes.

**Comment by StarpTech** [comment] 2022-02-27 14:26
Hi @Thisen, good to hear that you found it. Since atoms are functions with business logic, it would be very bad DX if React refresh is not fully supported. For my use case, it's already a mess because I need to reload my page for every change in an atom.

**Comment by dai-shi** [comment] 2022-02-28 01:30
@Thisen Would it be possible to use Function.toString() and see if the code is changed?

@StarpTech This is a very difficult problem, but I understand it'd be nice to fix. If you have suggestions/ideas, you are very welcome. In essence, we need to learn how React deals with it and follow what it does.
Meanwhile, to help DX with Fast Refresh, I'd suggest to define each atom in a file. `store/postIdAtom.js`, `store/postId.js` and so on, and re-export from `store.js`.

**Comment by StarpTech** [comment] 2022-02-28 13:05
>  but I understand it'd be nice to fix

I'll try to look into it as well. It's definitely not just nice :) It doesn't fall back to hot reload. The application will no longer work because the states aren't updated when a state is changed.

**Comment by StarpTech** [comment] 2022-02-28 14:02
@dai-shi how do you handle that in your workflow?

**Comment by Thisen** [comment] 2022-02-28 16:55
Hi @StarpTech, could you try out the build in #1030?

**Comment by StarpTech** [comment] 2022-02-28 20:29
Unfortunately, doesn't help. After changing a string in an atom function that is used in a parent and children relationship, the parent no longer receives updates.

**Comment by dai-shi** [comment] 2022-02-28 22:40
> @dai-shi how do you handle that in your workflow?

👇 



> Meanwhile, to help DX with Fast Refresh, I'd suggest to define each atom in a file. `store/postIdAtom.js`, `store/postId.js` and so on, and re-export from `store.js`.

I don't know if it works your case, though.

**Comment by StarpTech** [comment] 2022-03-01 15:56
@dai-shi I tried but without success.

**Comment by dai-shi** [comment] 2022-03-01 22:32
> I tried but without success.

Hmm, I need to look into it. Would you be able to share a codesandbox repro?

**Comment by StarpTech** [comment] 2022-03-02 10:02
@dai-shi I shared two. Are they sufficient to start the work? I can try to provide another one.

**Comment by dai-shi** [comment] 2022-03-02 11:55
Yeah, if you have split `store/*.js` example, it's helpful.

**Comment by dai-shi** [comment] 2022-03-04 00:37
@StarpTech Here you go: https://codesandbox.io/s/quizzical-andras-q3tmze?file=/src/store.js

**Comment by Thisen** [comment] 2022-03-08 17:55
Is there more we can do here @dai-shi?

**Comment by dai-shi** [comment] 2022-03-08 23:20
@Thisen I'm still curious why this doesn't work. Would you investigate it please?

```js
const postIdAtom = atom(INITIAL_POST_ID);

export const postId = atom(
  (get) => {
    // update the number, will reset "postIdAtom"
    console.log(3);
    return get(postIdAtom);
  },
  (get, set, update) => set(postIdAtom, update(get(postIdAtom)))
);
```

Even without #1030, I expect `postIdAtom` should be cached, no?

**Comment by Thisen** [comment] 2022-04-13 07:55
> @Thisen I'm still curious why this doesn't work. Would you investigate it please?
> 
> ```js
> const postIdAtom = atom(INITIAL_POST_ID);
> 
> export const postId = atom(
>   (get) => {
>     // update the number, will reset "postIdAtom"
>     console.log(3);
>     return get(postIdAtom);
>   },
>   (get, set, update) => set(postIdAtom, update(get(postIdAtom)))
> );
> ```
> 
> Even without #1030, I expect `postIdAtom` should be cached, no?

It should 🤔 I'll look into it!

**Comment by Thisen** [comment] 2022-04-28 19:05
@dai-shi, I couldn't reproduce it - It should work with `jotai/babel/plugin-react-refresh`. You got a reproduction with the plugin?

**Comment by dai-shi** [comment] 2022-04-29 00:00
@Thisen https://github.com/pmndrs/jotai/issues/1025#issuecomment-1048647739 should be the reproduction, as far as I recall.

**Comment by Thisen** [comment] 2022-04-29 06:27
@dai-shi https://github.com/pmndrs/jotai/issues/1025#issuecomment-1053562626 I don't think we can support this scenario tbh. Then we need to redo the caching mechanism for the Babel plugin.

**Comment by Thisen** [comment] 2022-05-03 07:16
I still don't have a reproduction with our babel plugin.

**Comment by Thisen** [comment] 2022-05-03 12:11
@StarpTech do you have a reproduction?
I can't see the Babel plugin being configured in these examples: https://github.com/pmndrs/jotai/issues/1025#issuecomment-1048647739

If not, I will close the issue.

**Comment by alan-nf** [comment] 2022-06-02 20:56
@TwistedMinda I'm actually still completely stumped by https://github.com/pmndrs/jotai/issues/1150 so I'm in favor of calling this out as a DX issue. The other big bullet item I would add is:

* even when you split the atom out to a separate file it might get included in hot-update bundles and diagnosing WHY (e.g. in Vite) might be very difficult

**Comment by TwistedMinda** [comment] 2022-06-02 21:14
@alan-nf Yeah, alright, our best Fast Refresh wizards shall come once we raise the help flag.
Gonna make a PR

> it might get included in hot-update bundles and diagnosing WHY (e.g. in Vite) might be very difficult
Means that determining the reason why it was included in "hot-update bundles" might be difficult? (eg. in Vite) 
I got you right?

**Comment by dai-shi** [comment] 2022-06-02 23:10
Sorry for ambiguous issue status.
We were waiting for a repro. https://github.com/pmndrs/jotai/issues/1025#issuecomment-1116027007

Let's close this as stale.

#1203 seems a good suggestion. Let's continue.

**Closed by dai-shi** 2022-06-02 23:10 UTC
Labels: enhancement
