### ISSUE TITLE
`useHydrateAtoms` w/ NextJS sometimes persists previous value even on new page loads

### ISSUE THREAD

**Issue by arcoraven** [pmndrs/jotai#1190] opened 2022-05-29 05:41 UTC
I'm seeing a strange and intermittently reproducible issue with useHydrateAtoms and NextJS.

I have a page `/item/:item_id` where `getServerSideProps()` queries the item from DB and renders a page with that data. I added a `console.log(item)` in `getServerSideProps()` and in the React component that uses this atom.

Steps to reproduce:
- Navigate to `/item/1`
  - Server-side console logs `item 1`
  - Client-side console logs `item 1`
- Open a new tab, navigate to `/item/2`
  - Server-side console logs `item 1`
  - Client-side console logs `item 2`
  - NextJS throws a client-side warning:
    - > Warning: Prop `alt` did not match. Server: "Item 1" Client: "Item 2"

**Result:** Some elements on the page render item 2's data, and some (like images) render item 1's data.

Code (simplified for readability):
```typescript
const myItemAtom = atom<MyItem | undefined>(undefined)

function MyItemPage({ item }: { item: MyItem }) {
  useHydrateAtoms([[myItemAtom, item]]);
  return (
    <>
      <ItemMetadata />
    </>
  )
}
export default MyItemPage;

export const getServerSideProps({ query }) {
  const item = // retrieve item with ID `query.item_id`
  console.log(item.id)
  return { props: { item } }
}

// in another file
export function ItemMetadata() {
  const item = useAtomValue(myItemAtom)
  console.log(item.id)
  return (
    <>
      <Text>{item.name}</Text>
      <Image src={item.image_url} alt={item.name} />
    </>
  )
}
```

So on subsequent page loads (even on a _new tab_) NextJS seems to be loading an old/existing value for the atom instead of the newest value. I understand that hydration is meant to be done once and does not change with re-renders, but is there some caching or storage happening that causes the value to persist across sessions?

Note: Setting the atom in a `useEffect` instead of using `useHydrateAtoms` fixes the consistency issue, but it's less elegant and has an initial delay where the values are not properly set.

Thanks in advance for the help!

**Comment by dai-shi** [comment] 2022-05-29 13:32
Just some quick questions / comments without looking in detail:
- Do you use `Provider`?
- `useHydrateAtoms` can only set values if atoms are not initialized. (If `useEffect` works, it sounds the case of initialized atoms.)
- If you use Provider, and clean up by remounting, `useHydrateAtoms` would work as expected.

We are still at the stage to collect use cases / best practices of `useHydrateAtoms`.

**Comment by arcoraven** [comment] 2022-05-29 19:04
Thanks for the quick response @dai-shi.
- I am not using `Provider` nor any scopes. Should I be? My app should not require reading the same atom and expect different values in different contexts. But I do expect a new page load or page refresh to wipe and reset all atom state (except any `atomWithStorage` usage).
- Could you clarify a bit more what you mean by initialized? I declare my atoms as a global export like the example:
```typescript
// in /lib/atoms/item.ts
export const myItemAtom = atom<MyItem | undefined>(undefined);
```
and `useHydrateAtom` is the first line in my page component. I'm not setting this atom anywhere else. But my expectation is this line initializes the atom to `undefined`. Is there an alternative to this?

**Comment by dai-shi** [comment] 2022-05-29 23:14
It sounds like we were failing to give a proper expectation.
Putting it simply, if you hydrate an atom once, you can never do it again unless totally clearing it with remounting `<Provider>`.
So, using `useEffect` for the second time is the correct approach.
(Sorry, "initialized" was a wrong term in this case.)

**Comment by arcoraven** [comment] 2022-05-30 04:13
So does my behavior sound expected?

What confused me the most is that refreshing the page or opening a new tab persisted the atom's initial value. My understanding of atoms is that they are data stored in-memory on the client, and reloading the page should cause all components to remount, thus having the atom be set to the initial state (in my case, `undefined` then hydrated with the db value).

**Comment by dai-shi** [comment] 2022-05-30 05:30
Do you think you can reproduce the confusing behavior with codesandbox without nextjs?

**Comment by qhnu** [comment] 2022-06-02 12:49
I suffered from a similar phenomenon.
I am using Remix, but any framework that uses SSR will have the same problem.

For example in the following cases.

1. Get **`userA`**'s email address on the server side and SSR it.

```ts
const emailValue = userA.email
useHydrateAtoms([[emailAtom, emailValue]])
```

2. A different request for **`userB`** comes in, SSR it in the same way.
```ts
const emailValue = userB.email
useHydrateAtoms([[emailAtom, emailValue]])
```

3. **`userB`**'s html now shows **`userA`**'s email address 😱.

This is happening because the server side still has the status of the previous request.
I commented out the following line to make it work correctly
```patch
--- a/node_modules/jotai/esm/utils.mjs
+++ b/node_modules/jotai/esm/utils.mjs
@@ -648,11 +648,12 @@ function useHydrateAtoms(values, scope) {
   const hydratedSet = getHydratedSet(scopeContainer);
   const tuplesToRestore = [];
   for (const tuple of values) {
-    const atom = tuple[0];
-    if (!hydratedSet.has(atom)) {
-      hydratedSet.add(atom);
-      tuplesToRestore.push(tuple);
-    }
+    // const atom = tuple[0];
+    // if (!hydratedSet.has(atom)) {
+    //   hydratedSet.add(atom);
+    //   tuplesToRestore.push(tuple);
+    // }
+    tuplesToRestore.push(tuple);
   }
   if (tuplesToRestore.length) {
     store[RESTORE_ATOMS](tuplesToRestore);

```


However, it would be great to have a beautiful solution rather than this ugly patch fix.

**Comment by dai-shi** [comment] 2022-06-02 12:53
> I commented out the following line to make it work correctly

Yeah, but this breaks React rule.



> 2\. A different request for **`userB`** comes in, SSR it in the same way.

Okay, I'm pretty sure you should use `<Provider>` and SSR should use a new provider if a user changes. Or, just a session. Provider-less mode is a bad idea for SSR.

**Comment by qhnu** [comment] 2022-06-02 13:09
Thank you!
I will use `<Provider>` you suggested.
This is a great solution, better than a patch.
[https://jotai.org/docs/api/core#provider](url)

**Comment by dai-shi** [comment] 2022-06-03 11:41
While we name it `useHydrateAtoms` with SSR use case in mind, its logic is simple and not limited to SSR.
 I can't think of using SSR without `Provider`, so we should update NextJS doc. Would you take it?

> I translate "not initialized" to "not have a value yet", is it correct?

Correct. I mis-used the term "initialized" there.
`Provider` is very important in Jotai as it's React Context based. It gives us more control on lifecycle.
The only use case that provider-less mode works is, a) you would have only one `<Provider>` at the root of your app, and b) only one your app instance exists in JS memory. SSR doesn't apply b), as it creates new instance for each session. (I hope the terminology is understandable.)

**Comment by TwistedMinda** [comment] 2022-06-03 12:08
Closing the issue in favor of the PR

**Closed by TwistedMinda** 2022-06-03 12:08 UTC
Labels: work in progress

**Comment by smontlouis** [comment] 2022-09-02 09:18
Am I missing something ? Just tried to use `Provider` with `useHydrateAtoms` and I still have the issue.
Should I use scope, or initialValues ?

**Comment by smontlouis** [comment] 2022-09-02 09:40
I'm using NextJS.

_document.tsx
```
...
          <JotaiProvider>
            <Main />
          </JotaiProvider>
...
```


in _app.tsx
```
...
  useHydrateAtoms([
    [userThemeAtom, cookies?.userThemeAtom],
    [browserThemeAtom, cookies?.browserThemeAtom],
    [userDarkThemeAtom, cookies?.userDarkThemeAtom],
    [userLightThemeAtom, cookies?.userLightThemeAtom],
  ])

  const [userTheme] = useAtom(userThemeAtom)
  const [browserTheme] = useAtom(browserThemeAtom)
  const [lightTheme] = useAtom(userLightThemeAtom)
  const [darkTheme] = useAtom(userDarkThemeAtom)

```


Previous values persist.

**Comment by dai-shi** [comment] 2022-09-02 12:40
> Am I missing something ? Just tried using `Provider` with `useHydrateAtoms` and I still have the issue.

Be reminded that `useHydrateAtoms` will only set values *if* atoms are not yet initialized in store. For the second time, it will be NO-OP.

**Comment by smontlouis** [comment] 2022-09-02 14:48
I'm not sure I fully understood what you meant.

User can have light / dark theme, and I want to hydrate atoms with cookies.
The issue I'm having right now is the same as op.

First page load, everything is fine. Then I change theme to `dark`, reload the page, but atom is still `light`, despite cookie being  `dark`.
I thought wrapping with a Provider would fix the issue.

What should be done ?

**Comment by dai-shi** [comment] 2022-09-02 15:12
`useHydrateAtoms` can only be used for **the very first time**. So, you can't use it to sync with cookies. `atomWithStorage` is for you. (I remember someone was trying to use it with cookies.)

(If you remount `Provider`, then you can use `useHydrateAtoms`. It's not what you probably want.)

**Comment by johnny-mh** [comment] 2023-05-25 02:58
Can I ask a question? useHydrateAtoms allows convenient specification of initial state values at runtime. However, when these specified initial values need to be updated due to changes in the props received from the parent component, the code tends to become messy. What can be done to address this?

```tsx
const HydrateAtoms = ({ initialValues, children }) => {
  // initialising on state with prop on render here
  useHydrateAtoms(initialValues)
 
  // ++ ADDED CODES ++
  const isFirstRender = useRef(true)
  const [,setState] = useAtom(textAtom)

  useEffect(() => {
    if (isFirstRender.current) {
      isFirstRender.current = false
      return
    }

    setState((prev) => ({ ...prev, ...initialValues[0][1] }))
  }, [initialValues])
  // ++ ADDED CODES ++

  return children
}

export const TextDisplay = ({ initialTextValue }) => (
  <Provider>
    <HydrateAtoms initialValues={[[textAtom, initialTextValue]]}>
      <PrettyText />
      <br />
      <UpdateTextInput />
    </HydrateAtoms>
  </Provider>
)
```

**Comment by dai-shi** [comment] 2023-05-25 12:08
It looks good. I would try to avoid `useRef`.
Assuming, `initialValue` is stable unless changed, here's the simpler one:
```js
const HydrateAtoms = ({ initialValues, children }) => {
  // initialising on state with prop on render here
  useHydrateAtoms(initialValues)
 
  // ++ ADDED CODES ++
  const setState = useSetAtom(textAtom)
  useEffect(() => {
    setState((prev) => prev === initialValue ? prev : { ...prev, ...initialValues[0][1] })
  }, [setState, initialValues])
  // ++ ADDED CODES ++

  return children
}
)
```

**Comment by johnny-mh** [comment] 2023-05-25 14:34
@dai-shi Thank you kindly for your response!

**Comment by parsagholipour** [comment] 2024-12-30 11:55
I had this issue with SSR and fixed with the following method:
```js
import { type RenderToPipeableStreamOptions, renderToPipeableStream } from 'react-dom/server'

export function render(_url: string, props: any, _ssrManifest?: string, options?: RenderToPipeableStreamOptions) {
const store = createStore();
  return renderToPipeableStream(
    <Provider store={store}>
      <App {...props} />
    </Provider>, options
  )
}
```

**Comment by richardantao** [comment] 2025-01-04 04:17
In Next 15, I think this problem is resolved with the separate package `jotai-ssr`.

**Comment by songkeys** [comment] 2025-11-08 20:08
I have a question. Looks like in ssr framework, we should wrap the app with `<Provider>`, and if using custom `store`, create it on request:

(i'm using tanstack start)

```tsx
// src/routes/__root.tsx
import * as React from 'react'
import { Provider, createStore } from 'jotai'
import {
  createRootRoute,
  Outlet,
  HeadContent,
  Scripts,
} from '@tanstack/react-router'

export const Route = createRootRoute({
  component: Root,
})

function Root() {
  // One store per SSR request and per client session:
  const [store] = React.useState(() => createStore())

  return (
    <html>
      <HeadContent />
      <body>
        <Provider store={store}>
          <Outlet />
        </Provider>
        <Scripts />
      </body>
    </html>
  )
}
```

But in this case, how do i access the `store` variable outside of react components / hooks? sometimes i may want to access `store.get` and `store.set` in non-react/hooks functions for convenience.

In this doc: https://github.com/pmndrs/jotai/blob/main/docs/guides/using-store-outside-react.mdx , it shows we `createStore()` outside of react component so that we can access it outside as well. But in ssr case, there seems no possible way to do so?
