### ISSUE TITLE
Extra re-renders with selectable list

### ISSUE THREAD

**Issue by moroshko** [pmndrs/jotai#1175] opened 2022-05-20 13:16 UTC
Given a list of selectable items, when an item's selection is toggled, I'd like only that item to be re-rendered.
However, I see that ALL items are getting re-rendered.
What am I doing wrong?

Use case: Select items to perform bulk action of the selected item ids.

[CodeSandbox](https://codesandbox.io/s/jotai-select-list-forked-nljpsh)

**Comment by dai-shi** [comment] 2022-05-20 14:11
https://codesandbox.io/s/jotai-select-list-forked-p4zzwk

Nothing is wrong. React runs render function and finds that atom values are the same, and stop rendering (no commit). This behavior is basically the same as `useReducer`.

**Comment by TwistedMinda** [comment] 2022-05-20 15:13
@moroshko I think your algorithm could be improved if you really need to focus on performances.

Here is a schema of your pattern:
- create map of <string, atom>
- for each item, create a derived atom on the map, for a given id
- everytime you update one toggle in your list
  - this will re-render all your items
  - as dai-shi mentioned it's not a big deal because there will be no commits by react (but it's still not ideal)

Here's how you couold avoid the extra re-renders:

- for each list item create a read-write atom<boolean> like you did, **except not depending on the map atom**
- of course, you will need to fill up the initial value for each row at the first render
```tsx
const selectedAtom = atom<Record<string, boolean>>({});
const Item = (props) => {
  const { item, initialSelection } 
  const reference = React.useRef(atom(props.initialSelection))
  const [toggle, setToggle] = useAtom(reference.current)
  // ...
  return (null)
}
const List = (props) => {
  const renderItem = (item) => {
    const value = props.initialSelection[item.id]
    return (
       <Item item={item} defaultValue={value} />
    )
  }
  return items.map(renderItem)
}
const Component = () => {
  const initialValues = useAtomValue(selectedAtom)
  // Stop listening changes after first mount
  const MemoizedList = React.useMemo(() => <List initialValues={initialValues} />, [])
  return (
    <MemoizedList />
  )
}
```

That way, only the toggle item is the only one re-rendered.

**Comment by TwistedMinda** [comment] 2022-06-02 19:45
@dai-shi I think we can close it as it's all intended behaviour. I even tried to provide a work-around if needs be to avoid extra-renders (can't remember if I tested it, tho, but looks more like a react problem than jotai problem anyway)

OP could still add a comment to re-open if need more info.

**Comment by dai-shi** [comment] 2022-06-02 22:39
Yeah.
Would it be nice if we could describe such a behavior is expected in docs somewhere?

**Comment by TwistedMinda** [comment] 2022-06-02 22:54
@dai-shi Yeah. We could add a "Performance" guide. It would tackle:

- the expected behaviour that needs to be kept in mind when having atoms depending on other ones (that they all re-calculate when their parent changes)
- utils `focusAtom` & `selectAtom`, can't hurt
- `useMemo` & `useCallback` for stable references one more time, can't hurt
- quick comparison with flux (selectAtom) & proxies (valtio) and in which use case they theoretically perform better

Otherwise, I don't know where to put something like this, it's pretty much how react behaves too: re-render the parent will re-caclulate the children (aka useReducer)

I could try to propose a PR for this, I'm pretty interested in this topic

**Comment by dai-shi** [comment] 2022-06-02 23:13
No, I didn't mean "Performance" guide, which sounds interesting as another topic though.

What I mean is, extra re-render without commit is an expected/intentional behavior, which is the default behavior of useReducer in React 18, and nothing needs to be worried.

**Comment by TwistedMinda** [comment] 2022-06-02 23:26
@dai-shi Well, that fits performance concerns to me :p Why would someone care about extra-renders if not for saving some calculation for performance purposes?

Where else would you put that note? When first talking about derived atoms in "Primitves" ?

> No, I didn't mean "Performance" guide, which sounds interesting as another topic though.

I'll think about it

**Comment by dai-shi** [comment] 2022-06-03 02:54
> @dai-shi Well, that fits performance concerns to me :p Why would someone care about extra-renders if not for saving some calculation for performance purposes?

I know where you come from, but I strongly want to discuss from a different angle.
This behavior is just a normal behavior, like useReducer.
Basically, render functions should be lightweight as React can call it multiple times.
If extra calculation is the concern, `useMemo` should help, and it's the React pattern regardless of jotai. (So, mentioning such a pattern in "Performance" guide makes sense.)

> Where else would you put that note? When first talking about derived atoms in "Primitves" ?

That sound like a good idea.

btw, @sandren and I talked about an idea of combining "Primitive" section and "Core API" section.

**Comment by TwistedMinda** [comment] 2022-06-03 03:14
@dai-shi 

> I know where you come from, but I strongly want to discuss from a different angle.

😅😅

>>When first talking about derived atoms in "Primitves" ?
> That sound like a good idea.

Yeah sounds resaonable. Its just gonna be a "Note:" after all, and its pretty core/primitive related. I got convinced again!

> This behavior is just a normal behavior, like useReducer.
Basically, render functions should be lightweight as React can call it multiple times.

Yup. And we can't omit it in our future Performance tab, right? :p 
I already mentioned it at the [last sentence](https://jotai.org/docs/guides/react-native) for RN but it doesn't feel right that it's only there.

> If extra calculation is the concern, useMemo should help, and it's the React pattern regardless of jotai. (So, mentioning such a pattern in "Performance" guide makes sense.)

Yup

> btw, @sandren and I talked about an idea of combining "Primitive" section and "Core API" section.

Yep this was part of one of my proposition too, for re-ordering the menu. Looking forward to it!

**Comment by TwistedMinda** [comment] 2022-06-03 13:11
Closing it in favor of the 2 seperate PR's.

**Closed by TwistedMinda** 2022-06-03 13:11 UTC
Labels: work in progress
