### ISSUE TITLE
[Question]: is it possible to read stale data?

### ISSUE THREAD

**Issue by Andreyco** [pmndrs/jotai#199] opened 2020-11-17 00:06 UTC
Is it possible to read stale data while another async read operation is running?

As soon as read operation is being executed, `Suspense` switches to `fallback` node. I wonder whether jotai can help it in any way.

**Comment by dai-shi** [comment] 2020-11-17 00:31
There's no api to read stale data while suspending.

However, we can avoid suspense to fallback for `write`.
If you don't return a promise, it will not suspend.

```js
const dataAtom = atom({})
cosnt fetchDataAtom = atom(
  (get) => get(dataAtom), // or whatever
  (get, set, url) => {
    const fetchData = async () => {
      const response = await fetch(url)
      const data = await response.json()
      set(dataAtom, data)
    }
    fetchData()
  }
)
```

For `read`, it's not possible by design (at least, I suppose so for now).
If you need to control loading state on your own, I suggest to try `write` instead of async `read`. Not quite sure if it works for your use case, though.

Or, maybe keeping a last value in a ref might work.
```js
const [data] = useAtom(dataAtom)
useEffect(() => {
  lastDataRef.current = data // the ref is defined outside Suspense
})
```

**Comment by dai-shi** [comment] 2021-06-21 11:38
Closing this as answered.
See also https://docs.pmnd.rs/jotai/guides/no-suspense

**Closed by dai-shi** 2021-06-21 11:38 UTC
Labels: has snippet
