### ISSUE TITLE
splitAtom(arrayAtom) returns inconsistent length temporarily with multiple renderers since v1.3.3

### ISSUE THREAD

**Issue by sxy8469** [pmndrs/jotai#728] opened 2021-09-22 15:15 UTC
const itemsAtom = atom([])
const itemAtomsAtom = splitAtom(itemsAtom)

const items= useAtomValue(itemsAtom );
const itemAtoms= useAtomValue(itemAtomsAtom);
**items.length ≠ itemAtoms.length ???**

**Comment by dai-shi** [comment] 2021-09-22 15:33
Thanks for reporting. This seems unexpected.
Would you be able to create a minimal reproduction in codesandbox?

It works in v1.3.2, but not v1.3.3, right?
Either #678 or #689 might cause an issue. 🤔

**Comment by sxy8469** [comment] 2021-09-23 06:29
> Thanks for reporting. This seems unexpected.
> Would you be able to create a minimal reproduction in codesandbox?
> 
> It works in v1.3.2, but not v1.3.3, right?
> Either #678 or #689 might cause an issue. 🤔

https://codesandbox.io/s/react-typescript-forked-gi301?file=/src/App.tsx

**Comment by dai-shi** [comment] 2021-09-23 10:21
> It works in v1.3.2, but not v1.3.3, right?
> Either #678 or #689 might cause an issue. 

Either #687 or #689, and it's #687 causing this.

**Comment by dai-shi** [comment] 2021-09-23 10:24
Hm, `removePoint` removes the original array. A bit of surprising it's working pre v1.3.3.
Let me see if I can repro in tests.

**Comment by dai-shi** [comment] 2021-09-23 11:14
Okay, I found the issue is not reproducible if we don't use react-konva.

**Comment by sxy8469** [comment] 2021-09-26 13:00
> Okay, I found the issue is not reproducible if we don't use react-konva.

Yes, but the "react-konva" is required.
I still hope this problem can be solved in the next version

**Comment by dai-shi** [comment] 2021-09-26 13:42
But, we don't know what is the problem, thus we can't investigate a possible solution. We would like to fix it for sure. Do you happen to know how react-konva works? Or, can you try to reproduce the issue without react-konva?
Meanwhile, this is a workaround: https://codesandbox.io/s/react-typescript-forked-6dqs8

**Comment by sxy8469** [comment] 2021-09-27 01:41
> But, we don't know what is the problem, thus we can't investigate a possible solution. We would like to fix it for sure. Do you happen to know how react-konva works? Or, can you try to reproduce the issue without react-konva?
> Meanwhile, this is a workaround: https://codesandbox.io/s/react-typescript-forked-6dqs8

Thanks,  I temporarily reverted to 1.3.2 version   : )

**Comment by sxy8469** [comment] 2021-09-27 02:57
This problem also occurs when using "@inlet/react-pixi".
It should be caused by using "ReactFiberReconciler"

Example：
https://codesandbox.io/s/react-typescript-forked-wwyru?file=/src/App.tsx

**Comment by dai-shi** [comment] 2021-09-27 03:00
We need somebody to help on this.
If anyone is interested or got challenged, please try to create a reproduction of the issue without react-konva.

**Comment by dai-shi** [comment] 2021-09-27 03:03
> This problem also occurs when using "@inlet/react-pixi".
> It should be caused by using "ReactFiberReconciler"

Oh, that's good to know! Then, I guess it would be extremely hard to solve this now.
But, the good new is when React 18 comes, it would probably batch actions, so hopefully it will work.

**Comment by dai-shi** [comment] 2021-09-27 03:16
So, given that this is not solvable, my suggestion is to use (read) only the result of `splitAtom`, not mixing with the original arrayAtom (of course, we need to mutate arrayAtom).

Here's the fix: https://codesandbox.io/s/react-typescript-forked-6u6pe?file=/src/App.tsx

Hope it helps.

**Comment by dai-shi** [comment] 2021-11-30 09:40
@Thisen We might be interested if #854 changes the behavior. Otherwise, we can close this as `wontfix`. Or, you can dig into it. I'm happy if you rebuild `splitAtom` from scratch.

**Comment by dai-shi** [comment] 2021-12-30 12:06
Unfortunately, v1.5.0 doesn't change the behavior. Please use [the workaround](https://github.com/pmndrs/jotai/issues/728#issuecomment-927494509).
Let me close this as wontfix. That doesn't mean to stop someone to challenge it.

**Closed by dai-shi** 2021-12-30 12:06 UTC
Labels: on hold
