### ISSUE TITLE
[BUG]  derived atoms don't update depended on other atoms which update when router back

### ISSUE THREAD

**Issue by SquirrelJimmy** [pmndrs/jotai#490] opened 2021-05-23 15:03 UTC
I use derived atoms filterTodoList, that depends on filterState, I don't use Provider, when I navigate to other page and go back, 
I can update filterState but filterTodoList doesn't update automatic, this is link for recurrent：https://codesandbox.io/s/jovial-shadow-4qnd8.  
![动画](https://user-images.githubusercontent.com/24666536/119265874-fcb7af00-bc1a-11eb-8de6-c83b5583737a.gif)

I find in source code:
![image](https://user-images.githubusercontent.com/24666536/119265470-79498e00-bc19-11eb-8d24-8865c550191a.png)
not working!  
![image](https://user-images.githubusercontent.com/24666536/119265496-9a11e380-bc19-11eb-8afc-4f34c949c2d9.png)
make `listeners.delete(callback)` and `delAtom(state, atom)` reverse order, it's working!

**Comment by dai-shi** [comment] 2021-05-23 22:00
Wow, nice catch!
The fix seems fairly reasonable, but it makes existing tests to fail. (There should be other places to fix in addition, maybe.) 🤔 

Would you be interested in working on a PR?
We should have a test for this too. (How can we test such a behavior?)
A failing test without a fix would still be helpful.

**Comment by sex-squirrel** [comment] 2021-05-24 01:21
> Wow, nice catch!
> The fix seems fairly reasonable, but it makes existing tests to fail. (There should be other places to fix in addition, maybe.) 🤔
> 
> Would you be interested in working on a PR?
> We should have a test for this too. (How can we test such a behavior?)
> A failing test without a fix would still be helpful.

yeah, I will have a try when I have a cup of tea

**Comment by sex-squirrel** [comment] 2021-05-24 08:59
> Wow, nice catch!
> The fix seems fairly reasonable, but it makes existing tests to fail. (There should be other places to fix in addition, maybe.) 🤔
> 
> Would you be interested in working on a PR?
> We should have a test for this too. (How can we test such a behavior?)
> A failing test without a fix would still be helpful.

![image](https://user-images.githubusercontent.com/24666536/119310434-4eefe300-bca2-11eb-8d62-39b7cf863eaf.png)
> this function `XXX doesn't work with mutally dependent atoms`, onece a atom has been unMounted, all depends lost

**Comment by dai-shi** [comment] 2021-05-24 09:27
Ah, that function. As noted, it's not implemented perfectly. 😓 
So, does it mean the bug is caused because it unmounts some atoms that shouldn't be unmounted?
(that explains why swapping deleteAtom and listeners.delete seems to fix the issue.)

**Comment by sex-squirrel** [comment] 2021-05-24 13:26
> Ah, that function. As noted, it's not implemented perfectly. 😓
> So, does it mean the bug is caused because it unmounts some atoms that shouldn't be unmounted?
> (that explains why swapping deleteAtom and listeners.delete seems to fix the issue.)
> 
> wait, I misunderstood. the `XXX` comment means it will not unmount atoms that should be unmounted.

emmm....I think some atom unMounted, if it's depends alive, that mounted again, it's deps is new, not the first deps! recoil has not the issue I have tried yet

**Comment by dai-shi** [comment] 2021-05-24 14:09
Hm, it's pretty obvious that this is some bug around unmount. But, I'm not exactly sure the root cause of the bug.
Would you be able to create a failing test? Maybe in `tests/dependency.test.tsx`.

**Comment by dai-shi** [comment] 2021-05-26 23:35
I made a failing test in https://github.com/pmndrs/jotai/tree/fix/issue-490. I hope this is the one in this issue.

**Comment by dai-shi** [comment] 2021-05-27 01:35
https://codesandbox.io/s/ancient-morning-gvkuk
Fixed by #498

**Comment by sex-squirrel** [comment] 2021-05-27 07:17
> https://codesandbox.io/s/ancient-morning-gvkuk
> Fixed by #498

I also find just now 
![image](https://user-images.githubusercontent.com/24666536/119782252-84910800-befe-11eb-931e-0b08b7c788dc.png)
![image](https://user-images.githubusercontent.com/24666536/119782323-a4283080-befe-11eb-83fb-68d6e0d7643c.png)

**Comment by sex-squirrel** [comment] 2021-05-27 07:22
> https://codesandbox.io/s/ancient-morning-gvkuk
> Fixed by #498

please release soon, I waite for this to show someone a using case which used jotai😸😸

**Closed** 2021-05-27 07:54 UTC
Labels: bug

**Comment by dai-shi** [comment] 2021-05-27 07:56
You can just use the codesandbox build if you are in hurry.

https://ci.codesandbox.io/status/pmndrs/jotai/pr/498/builds/134242

```bash
yarn add https://pkg.csb.dev/pmndrs/jotai/commit/8c941054/jotai
npm i https://pkg.csb.dev/pmndrs/jotai/commit/8c941054/jotai
```

**Comment by SquirrelJimmy** [comment] 2021-05-27 09:57
> You can just use the codesandbox build if you are in hurry.
> 
> https://ci.codesandbox.io/status/pmndrs/jotai/pr/498/builds/134242
> 
> ```shell
> yarn add https://pkg.csb.dev/pmndrs/jotai/commit/8c941054/jotai
> npm i https://pkg.csb.dev/pmndrs/jotai/commit/8c941054/jotai
> ```

thank you so mach!
