### ISSUE TITLE
Failed to pass tests with latest React experimental builds

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#1498] opened 2022-10-27 00:22 UTC
#1497 reveals that a test fails with versions between:
https://www.npmjs.com/package/react/v/0.0.0-experimental-79c582981-20221021
and
https://www.npmjs.com/package/react/v/0.0.0-experimental-fecc288b7-20221025.

**Comment by dai-shi** [comment] 2022-10-27 00:27
https://github.com/facebook/react/compare/65e32e58b...79c582981

<img width="601" alt="image" src="https://user-images.githubusercontent.com/490574/198163169-53310788-96f3-4d6e-86b4-2aa5a3869330.png">

We probably need to use `use`.

**Comment by dai-shi** [comment] 2022-10-31 07:22
#1512 still fails.
I'm not sure if the problem is on our end, or react, or testing-library.

Can anyone help?

**Comment by manakuro** [comment] 2022-11-16 04:42
It seems like some tests in `tests/utils/atomWithObservable.test.tsx` got stuck while executing. I'm going to dig into that.

https://github.com/pmndrs/jotai/blob/820f2f10aa380412646e2e26b461b4e1ecd23c44/tests/utils/atomWithObservable.test.tsx#L138

**Comment by manakuro** [comment] 2022-11-17 00:14
Turns out that the promise inside atomWithObservable is still pending after resolving, then the process got stuck.  
https://github.com/pmndrs/jotai/blob/a85c1f7142808a86c95141a31d366ce17afd7382/src/utils/atomWithObservable.ts#L84

This causes only when the `initialValue` is not passed and the promise is used.

`react@18.3.0-next-65e32e58b-20221019` executes rendering after the promise is resolved, but `react@18.3.0-next-79c582981-20221021` doesn't. I guess it's related to the changes on `react@18.3.0-next-79c582981-20221021`. 

it works in the browser environment, though.
https://codesandbox.io/s/react-typescript-forked-forked-nr4wuk?file=/src/App.tsx

I will continue to work on that.

**Comment by manakuro** [comment] 2022-11-18 00:55
@dai-shi 
This behavior occurs when you use `jest.useFakeTimers` and promise inside custom hooks.  The rendering process got stuck while flushing the process inside the `act`. The cause of this might have something to do with the PR. I reported it, so we can keep track of what's going on.

https://github.com/facebook/react/pull/25523#issuecomment-1319398115

As another option, we could flush the promises manually like this.
https://github.com/manakuro/test-react-experimental/pull/1/files

But still, there are some tests that got stuck in the `tests/utils/atomWithObservable.test.tsx`, so I need to figure this out.

**Comment by dai-shi** [comment] 2023-03-31 02:09
@manakuro Could https://github.com/facebook/react/pull/26512 be related or not?

**Comment by manakuro** [comment] 2023-03-31 05:17
@dai-shi I'm not sure the https://github.com/facebook/react/pull/26512 has anything to do with our issue, but the new version, [18.3.0-next-1308e49a6-20230330](https://www.npmjs.com/package/react/v/18.3.0-next-1308e49a6-20230330) seems to have solved the fake timer issue. I have no idea, but it might be related to the changes.
https://github.com/facebook/react/compare/41110021f...1308e49a6


Please take a look at my PR.
https://github.com/pmndrs/jotai/pull/1860

**Closed** 2023-04-10 02:48 UTC
Labels: help wanted
