### ISSUE TITLE
The component is re-rendered the first time it is rendered.

### ISSUE THREAD

**Issue by lgwebdream** [pmndrs/jotai#1137] opened 2022-05-03 11:09 UTC
``` javascript
import { atom, useAtom } from 'jotai'

// Create your atoms and derivatives
const textAtom = atom('hello')
const uppercaseAtom = atom(
  (get) => get(textAtom).toUpperCase()
)

// Use them anywhere in your app
const Input = () => {
  const [text, setText] = useAtom(textAtom)
  const handleChange = (e) => setText(e.target.value)
  return (
    <input value={text} onChange={handleChange} />
  )
}

const Uppercase = () => {
  const [uppercase] = useAtom(uppercaseAtom)
  return (
    <div>Uppercase: {uppercase}</div>
  )
}

const App = () => {
    //Print twice
    console.log("rerender....")
  return (
    <>
      <Input />
      <Uppercase />
    </>
  )
}
```
The component is re-rendered the first time it is rendered. That is my console.log will be printed twice. I don't encounter this kind of problem when I use recoil and useState. Is there any way to solve it, thank you.

**Comment by Thisen** [comment] 2022-05-03 11:13
Hi! 

Can you make a Codesandbox with a reproduction? :)

**Comment by lgwebdream** [comment] 2022-05-03 11:22
> Hi!
> 
> Can you make a Codesandbox with a reproduction? :)
https://codesandbox.io/s/jotai-redered-demo-m3yt72?file=/src/App.js
a very simple demo,thank you very much

**Comment by lgwebdream** [comment] 2022-05-03 13:37
> Hi!
> 
> Can you make a Codesandbox with a reproduction? :)

When I just initialized and defined the state and didn't involve modifying it, he actually re-rendered the component. It's really not reasonable here. Can you fix it?

**Comment by zm8** [comment] 2022-05-03 15:53
> When I just initialized and defined the state and didn't involve modifying it, he actually re-rendered the component. It's really not reasonable here. Can you fix it? @Thisen

I think this is not a bug. React will double-call render-phase lifecycles in development only. See [issue](https://github.com/facebook/react/issues/17786)

Remove ```<StrictMode></StrictMode>```, it will render once.

**Comment by dai-shi** [comment] 2022-05-03 23:32
https://codesandbox.io/s/jotai-redered-demo-forked-1gm5y8

This still shows two "rerender" logs.
<img width="253" alt="image" src="https://user-images.githubusercontent.com/490574/166590597-4c2856c7-5838-4f0b-a389-c56b9d12f32e.png">

---

I suppose you are observing double-render-with-one-commit behavior in your app. Please wrap `console.log()` with `useEffect` to count commits. If you see one commit, it's the expected behavior.

**Comment by lgwebdream** [comment] 2022-05-04 02:14
thank you for your reply. useEffect this I definitely know to avoid the above problem. But what I want to ask is why does the initialization state cause the component to re-render? Shouldn't the normal logic be that the updated component that triggers loading will be rendered again. This is annoying me. When I use the following two ways it doesn't render twice.

``` javascript
  console.log("rerender....")
  const [text] = useState('hello');
```

``` javascript
  console.log("rerender....")
  const textState = atom({
    key: 'textState', 
    default: '', 
  });
  const [text] = useRecoilState(textState);
```
I like jotai very much, and the advantages are more obvious than the above two. However, the component is re-rendered after initialization but the state has not changed. If I do not put some code in useEffect, it will cause the second execution of the function. What is the general idea of ​​jotai's design?  @dai-shi

**Comment by dai-shi** [comment] 2022-05-04 05:01
> If I do not put some code in useEffect, it will cause the second execution of the function.

Please do put impure code in useEffect. It's not jotai rule, but react in general. `StrictMode` is to catch such misusages.

> What is the general idea of ​​jotai's design?

Now, this is very technical, but the goal of jotai is to make it concurrent react friendly as much as possible. This double-render-one-commit behavior is the workaround I learned from `useSubscription` from the React team previously.

Recoil also seems to try something, according to [this experiment](https://github.com/dai-shi/will-this-react-global-state-work-in-concurrent-rendering).

https://codesandbox.io/s/recoil-basic-demo-forked-17qbny?file=/src/App.js
Try this ☝️  and you will see an extra render when you first change the value. (It's different from jotai which does on the first render.

**Comment by mattbdc** [comment] 2022-05-04 05:05
@lgwebdream I hit the same eek initially (after removing StrictMode like @zm8 suggests - it is still double rendered first mount - but one commit - see fiber docs for more on commit). I just edited my answer as dai-shi has replied above but there was some more context on the Discord if this is helpful..

**Comment by Thisen** [comment] 2022-05-04 08:21
I'm closing this issue, since there's no issues :)

**Closed by Thisen** 2022-05-04 08:21 UTC
Labels: needs repro

**Comment by lgwebdream** [comment] 2022-05-04 08:32
Can you please give me a link？ @mattbdc

**Comment by mattbdc** [comment] 2022-05-04 10:16
https://discord.com/channels/740090768164651008/752920140483526677/966972799635832873
