### ISSUE TITLE
[Question] Where do atoms and derived atoms values 'live'?

### ISSUE THREAD

**Issue by fjcalzado** [pmndrs/jotai#84] opened 2020-10-04 07:36 UTC
Hi @dai-shi, first of all thank you for this library. It is great to have different options, approaches and improvements around the React state topic. Good job!

I'm playing a bit with it and trying to better understand what's happening under the hood, which use cases can be easily covered with jotai and which doesn't (if any). And several questions arised. I didn't check code yet, sorry, so my questions are based on guessing.

My first assumption when I saw the `Provider` wrapping the tree:
```
<Provider>
  <App />
</Provider>
```
and also based [on this quote](https://github.com/pmndrs/jotai/issues/13#issuecomment-698961443):
>  If you need React Context alternatives, Jotai comes with enough features

was to think that:

- [ ] Provider is kind of a contextual store where all the atom values live. Is that correct?

Also, for learning/debug purposes:

- [ ] Is there a way we can check atom values directly from its "store" without consuming them? Similar to what Redux DevTools offer.

**Comment by fjcalzado** [comment] 2020-10-04 07:36
I'll continue in this post

**Comment by dai-shi** [comment] 2020-10-04 07:44
> Provider is kind of a contextual store where all the atom values live. Is that correct?

Yes, totally. Provider holds a big `Map` of atom and atom values.

> Is there a way we can check atom values directly from its "store" without consuming them? 

I had thought about adding `useDebugValue` in Provider, which we already have in useAtom, but it wouldn't be very useful, because an atom is not printable. Maybe we could create a special serializer to show the big `Map`, but I'm not sure how.

**Comment by fjcalzado** [comment] 2020-10-04 08:26
Can I ask you why is not printable?

By the way, I edited my post 2 above with a new sample and question, maybe you missed it, sorry.

**Comment by dai-shi** [comment] 2020-10-04 08:42
> the user data is persisted in the Provider, so the second time PageA is mounted it has user data available.

Yes, it's by design and `read` must be pure (in react terms), so it's technically correct.
Notice if you unmount PageA, the value in Provider is garbage collected, and after that if you mount PageA again, it will re-run the `read`.

> My guess is this behaviour has something to do with referential equality for the atom, being different on each mount maybe?

No, it has nothing to do with ref equality. I would do the same if we used string keys.
This behavior is because we store atom values in Provider, and only initialize it once when we add it in Provider.

**Comment by dai-shi** [comment] 2020-10-04 08:45
> Can I ask you why is not printable?

I simply mean this:
```js
> const atomA = {}, atomB = {}
undefined
> const map = new Map()
undefined
> map.set(atomA, 1)
Map { {} => 1 }
> map.set(atomB, 2)
Map { {} => 1, {} => 2 }
```

We don't have anything to distinguish atomA from atomB when we print.
With string keys, this wouldn't be a problem.

**Comment by fjcalzado** [comment] 2020-10-04 16:45
> I simply mean this:

I see your point, you are right. The only way I come up with is to add an optional name upon atom creation with the only purpose of labelling it for debug/inspection:

```js
import { atom } from 'jotai'

const countAtom = atom(0, "count");
```

Although this could be confused with a string key (which is not). Another downside: it makes API dirtier.

**Comment by fjcalzado** [comment] 2020-10-04 18:24
Regarding the original topic...

> Notice if you unmount PageA, the value in Provider is garbage collected, and after that if you mount PageA again, it will re-run the read.

> This behavior is because we store atom values in Provider, and only initialize it once when we add it in Provider.

All right, so if I understood correctly, an atom value life cycle could be described more or less like this:
- We create an atom using `const myAtom = atom(read, write)`. We register `read` and `write` methods associated to the atom unique ID (the object reference that is returned).
- We consume an atom with the hook `useAtom(myAtom)`. Under the hood, provider's map is checked to see whether myAtom key has already been initialized or not:
  - Not initialized yet? Call `read` to initialize the value, add an entry in the map `myAtom => value`.
  - Already initialized? Just consume the value, it was initialized before.
- Atom value lifespan: `myAtom` value is kept alive as long as `myAtom` references are used by `useAtom` in our execution context. Otherwise, garbage collector kicks in and frees its corresponding entry in the Map.

If this is the case, then a Provider resembles a React Context with an important difference:
- In a react context, state lives in the context until it is unmounted (local state).
- In a jotai provider, state persistence is based on its usage ("not used? I'll remove it"). 

This is a cool optimization feature, it is handy for keeping state light. However, it also brings a concern. Imagine the following tree:

```js
<Provider>
  <AppFrame/>
  <Router>
    <Switch>
      <Route path="/" exact><Home /></Route>
      <Route path="/pageA" exact={true}><PageA /></Route>
      <Route path="/pageB" exact={true}><PageB /></Route>
    </Switch>
  </Router>
</Provider>
```
What if I want to keep `PageA` state across navigation? I mean, persist `PageA` state even if a navigate to PageB and come back.
- If I place pageA atoms whithin `PageA` component, they will be garbage collected when navigating a different branch in the router.
- If I move atoms to an upper component like `AppFrame` it will do the trick as this component never dies, but it feels like I am breaking encapsulation: if we want a distributed state, atoms for page A should be close to `PageA`.

Is there a way we can control when atom values must be garbage collected ?

**Comment by dai-shi** [comment] 2020-10-04 21:54
```js
const countAtom = atom(0, "count");
```

Actually, we don't need to change the public API.

```js
addAtomDebugLabel(countAtom, "count") // api for debugging
countAtom.debugLabel = "count" // or, even mutating atom directly
```

**Comment by dai-shi** [comment] 2020-10-04 22:20
> What if I want to keep PageA state across navigation? I mean, persist PageA state even if a navigate to PageB and come back.

If this happens in a batch it works fine, because we garbage collect in useEffect.
Otherwise, out of lack with the current implementation.

> Is there a way we can control when atom values must be garbage collected or they should be removed by design?
> I am wondering if having an abstraction like 'atom scope' makes any sense, so that you can place an atom scope in your tree and associate atoms to it. A scoped atom value shouldn't be removed until its scope is unmounted.

I prefer to avoid adding another abstraction. If the current implementation didn't work with some libraries or some use cases, we'd change the garbage collection strategy. Maybe delay gc a commit later of a few commits (but that's not very predictable.) 🤔

**Comment by fjcalzado** [comment] 2020-10-05 05:54
By the way, I created the following [sandbox](https://codesandbox.io/s/jotai-scope-scenario-n8j6u) with the scenario I mentioned before. 

> I prefer to avoid adding another abstraction

In that case, what about multiple & nestable providers? Same as we do with React context. That will add flexibility with no new concepts. Place a provider on top to have global state, drop another one down deeper for a more local state, etc. Does that violate design? You'd just need an extra mechanism to link atoms with providers.

>  we'd change the garbage collection strategy

Regarding garbage collector, I find both strategies useful, either "auto clean" or "let the state be". Actually, you could even need both at some point. Why not let user choose? Example:

```js
<GlobalProvider>
  <AppFrame/>
  <PageAProvider autoClean={false}>
  <Router>
    <Switch>
      <Route path="/" exact><Home /></Route>
      <Route path="/pageA"><PageA /></Route>
      <Route path="/pageB">
        <PageBProvider>
          <PageB />
        </PageBProvider>
      </Route>
    </Switch>
  </Router>
  </PageAProvider>
</GlobalProvider>
```

**Comment by dai-shi** [comment] 2020-10-05 11:02
> In that case, what about multiple & nestable providers?

Currently, the impl supports nested providers giving different contexts, just like normal React contexts. I'm not a big fan of changing this behavior.

> Does that violate design?

My question is how developers clean up atom values.

> `autoClean={false}`

This means never garbage collected, right? It leads memory leak potentially.

> https://codesandbox.io/s/jotai-scope-scenario-n8j6u?file=/src/app.tsx

Does it reveal the issue?

**Comment by fjcalzado** [comment] 2020-10-05 18:54
> Does it reveal the issue?
That [sandbox](https://codesandbox.io/s/jotai-scope-scenario-n8j6u?file=/src/app.tsx) is just a playground to show a simple scenario with navigation and an expensive atom. Navigate to page A, `userDataAtom` will initialize its value (via fetch), go to B and come back to A, a second initialization is done. What I wanted to say is that, using context you can avoid that second initialization.

> This means never garbage collected, right? It leads memory leak potentially.

No, it will be garbage collected as soon as its provider is unmounted.

> Currently, the impl supports nested providers giving different contexts, just like normal React contexts.

Yes, you can nest providers, but you cannot pair a certain atom with a certain provider, it just goes to the closer in the tree.

Example with context:

```js
const myHelloAtom = atom("hello");
const myWorldAtom = atom("world");

const MyComponent = () => {
  const [hello] = useAtom(myHelloAtom);
  const [world] = useAtom(myWorldAtom);

  return <p>{`${hello} ${world} from atoms`}</p>;
};

export const AppAtoms = () => (
  <Provider>
    <Provider>
      <MyComponent />
    </Provider>
  </Provider>
);
```
Both atom values live in the deeper provider (the closer one up in the tree), so in practice, the top level provider does nothing.

The same solution with context:
```js
const HelloContext = React.createContext();
const WorldContext = React.createContext();

const AnotherComponent = () => {
  const hello = React.useContext(HelloContext);
  const world = React.useContext(WorldContext);

  return <p>{`${hello} ${world} from context`}</p>;
};

export const AppContext = () => (
  <HelloContext.Provider value="hello">
    <WorldContext.Provider value="world">
      <AnotherComponent />
    </WorldContext.Provider>
  </HelloContext.Provider>
);
```
As a developer, I can decide which piece of state goes in every provider. 

This is just a quick example to illustrate that you cannot link atoms with a provider. There is no benefit in choosing the second approach over the first, I know, but in many other common scenarios [like this](https://codesandbox.io/s/jotai-scope-scenario-n8j6u?file=/src/app.tsx), having the possibility to decide where to place your providers and what atoms belong to each one would make things easy.

**Comment by dai-shi** [comment] 2020-10-05 22:34
> What I wanted to say is that, having to re-initialize part of your state just because you unmounted a component is not always desired.

That I understood.

> No, it will be garbage collected as soon as its provider is unmounted.

Yeah. I meant if the provider is not unmounted. We are on the same page.

> Yes, you can nest jotai providers, but you cannot pair a certain atom with a certain provider, it will stick to the closer ancestor.

Right.

> Both atom values live in the deeper provider (the closer one up in the tree), so in practice, the top level provider does nothing.

I start getting your point.

> having the possibility to decide where to place your providers and what atoms belong to each one would make things easier.

So your proposal is to add `autoclean` flag in Provider, and if it's `false`, we don't garbage collect. If not specified, the default is the current behavior (= garbage collected.)

It would be easy to implement, but I wonder if developers can effectively use it. Seems to me that there should be a better solution, or better api.

**Comment by dai-shi** [comment] 2020-10-06 00:55
OK, I have an idea: let Provider have a new WeakMap to save atom value before removing it, and reuse it on reinitializing it. It's an implementation detail. For users, it's like `autoclean` is always false. (Now, there might be a way to simplify the impl further. 🤔 )

**Comment by fjcalzado** [comment] 2020-10-06 18:49
> So your proposal is to add autoclean flag in Provider, and if it's false, we don't garbage collect. If not specified, the default is the current behavior (= garbage collected.)

Exactly, that was one of the proposal. The other one was to being able to assign atoms to a certain Provider, so you can completely mimick React Context and place Providers wherever you want along with its atoms.

> but I wonder if developers can effectively use it

It can be harsh to understand and use it, I agree. It is a trade off, the more flexibility you offer, the more powerful the library would be. The less flexibility the easier to use although with limitations.

I am just trying to think what would happen with typical scenarios and check if jotai suits my needs. That's what I am suggesting all this ideas. It doesn't have to be like that, of course. I just find useful this kind of debate to be aware of possible limitations and solutions

**Comment by dai-shi** [comment] 2020-10-15 11:15
> let Provider have a new WeakMap to save atom value before removing it, and reuse it on reinitializing it.

Done in #131. It's basically never removed.

**Comment by dai-shi** [comment] 2020-11-01 03:38
@fjcalzado Closing this now. Let me know if we continue discussion here (reopen) or you open a new issue to refresh discussion.

**Closed by dai-shi** 2020-11-01 03:38 UTC

**Comment by pengx17** [comment] 2021-09-09 03:34
> The other one was to being able to assign atoms to a certain Provider, so you can completely mimick React Context and place Providers wherever you want along with its atoms.

I find the discussions in the thread very helpful.
Anything news about this? Or maybe it is recommended to create atom ad-hoc and passing them around with normal React.Context?

**Comment by dai-shi** [comment] 2021-09-09 04:40
This discussion is mostly obsolete. #131 changed some old assumptions (fixed the issue).
Would you mind opening a new issue or preferably a new discussion, with some more description about your use case?

**Comment by pengx17** [comment] 2021-09-09 05:22
@dai-shi oh I see. So the new atom scope param introduced in #131 should be sufficient for fixing this issue right? I will take a look again.
Thanks for making this wonderful library BTW!

**Comment by dai-shi** [comment] 2021-09-09 05:26
Note that #640 changed the scope api a bit different. (the internal is the same.)
You are welcome!
