### ISSUE TITLE
get atom value of scope

### ISSUE THREAD

**Issue by sixmen** [pmndrs/jotai#619] opened 2021-07-28 04:27 UTC
I tried to get a value in setter. But it does not return a value in global provider, but a default value.

Is it a bug or a feature?

Here is the code.

```
import React from "react";
import { Provider, atom, useAtom } from "jotai";
import { useUpdateAtom } from 'jotai/utils';

const globalScope = Symbol();
const someGlobalAtom = atom("empty");
someGlobalAtom.scope = globalScope;

const someLocalAtom = atom("empty");

const actionAtom = atom(null, (get) => {
  console.log(`on Action ${get(someGlobalAtom)} / ${get(someLocalAtom)}`);
})

const Component = () => {
  const [someGlobal] = useAtom(someGlobalAtom);
  const [someLocal] = useAtom(someLocalAtom);
  const action = useUpdateAtom(actionAtom);

  return (
    <div>
      Value: {someGlobal} / {someLocal}
      <button onClick={action}>Action</button>
    </div>
  );
};

const App = () => (
  <Provider scope={globalScope} initialValues={[[someGlobalAtom, "global"]]}>
    <Provider initialValues={[[someLocalAtom, "local"]]}>
      <Component />
    </Provider>
  </Provider>
);

export default App;
```

`Value: global / local` is shown in the component as expected.
But when I clicked the button, `on Action empty / local` is printed on the console.

**Comment by dai-shi** [comment] 2021-07-28 06:07
Ah, nice catch. You can't used mixed scopes in a derived atom.
It's a feature or a limitation. We should show better error message. 🤔  (Now, I think `useAtom(atom, scope)` might have been a better abstraction... 😓 )

Atom scope is designed for library use case, and usually app code doesn't require it. There might be some interesting use case though.

**Comment by sixmen** [comment] 2021-07-28 07:59
I used jotai to separate states from view code.

Some states are for a small component, some are for a large component(e.g. a page component), and some are for the global component(app component)

So I placed two providers for a component, one is for the page layer, other is for the global layer (preserved while page changes).
I can use both atoms in a leaf component.

And I also separate actions(or reducers in redux?) using derived atom. (as in the above example)
(I cannot ensure that this is a normal use case)

----

I solved my problem with different approach. But I think it is good if I can use both atoms also in the derived atom like in a component.
(I don't know it needs fundamental changes)

My global states are like logged-in user profile and user-agent.

**Comment by dai-shi** [comment] 2021-07-28 09:12
Jotai Provider is to create a new separate world, just the same as React Context Provider and it's technically not possible to read an atom value in a different world.

> (I don't know it needs fundamental changes)

So, the answer is simply impossible by design.

(But, I understand your confusion. That was a good feedback. Thanks for this.)

The suggestion for your use case is not to rely on atom scope behavior, which doesn't work as you expected. And, seems like you already solve it.

**Comment by dai-shi** [comment] 2021-07-28 23:24
> We should show better error message.

Reopening for this.

**Comment by dai-shi** [comment] 2021-08-06 23:59
>  (Now, I think `useAtom(atom, scope)` might have been a better abstraction... 😓 )

I feel like I should do this. Let me create a new issue.

**Comment by dai-shi** [comment] 2021-08-07 00:15
Closing in favor of #639.

**Closed by dai-shi** 2021-08-07 00:15 UTC
