### ISSUE TITLE
selectAtom not working any more

### ISSUE THREAD

**Issue by joacub** [pmndrs/jotai#1987] opened 2023-06-14 02:16 UTC
## Summary

selectAtom is returning for async atoms always a promise which cause a hooks to return a throw (promise), we expect that the hook just return the state if the state is not ready then do not return the state and set the sate later.

but now it is imposible to use the hook as this always return an promise like error and never update the state.

**Comment by dai-shi** [comment] 2023-06-14 02:26
Please provide a minimal reproduction, preferably with https://csb.jotai.org.
I will close it for now and reopen it once provided.

**Closed by dai-shi** 2023-06-14 02:26 UTC

**Comment by dai-shi** [comment] 2023-06-14 02:27
If this is an issue with async behavior, I assume it can be reproduced without selectAtom.
Or, do you think it's selectAtom specific issue?

**Comment by dai-shi** [comment] 2023-06-14 02:31
> I will close it for now and reopen it once provided.

On second thought, I'm converting this to a discussion, because #1158 is a closed issue.
