### ISSUE TITLE
atomWithStorage and NextJS 13 (SSR) hydration problems

### ISSUE THREAD

**Issue by logemann** [pmndrs/jotai#1694] opened 2023-01-16 16:07 UTC
## Summary
When having a page with a form (client component -> "use client") with an atom backed object which maps to the fields and using atomWithStorage for surviving Browser Refresh, while filling out the form, we get hydration errors on browser refresh because the form HTML looks different on server (no values) compared to the client (values coming from browser storage). This is because client components also do "SSR" and they look different on server and client.

NextJS docs say that you should re-populate the form fields in useEffect, which is called AFTER hydration. I assume atomWithStorage does the population of the backing object before hydration thus giving that error. 

I am sure this can be solved outside of jotai but perhaps there is a way in jotai to populate the object after hydration somehow. This would make things MUCH easier.

**Comment by rtritto** [comment] 2023-01-16 20:42
Should be a duplicate of #1689

Try (https://github.com/pmndrs/jotai/issues/1689#issuecomment-1383844588):
```js
export const localStorageAtom = atomWithStorage('localVariableName', <initial_value>, {                
  ...createJSONStorage(() => localStorage),                                    
  delayInit: true                                                              
})
```

**Comment by dai-shi** [comment] 2023-01-17 00:55
We prefer using discussions to issues for questions (maybe we should say to include unconfirmed bugs?)
Please open a discussion before an issue.

**Closed by dai-shi** 2023-01-17 00:55 UTC
