### ISSUE TITLE
Clearer warning log for Atom State not found

### ISSUE THREAD

**Issue by tarngerine** [pmndrs/jotai#242] opened 2020-12-16 18:28 UTC
<img width="961" alt="image" src="https://user-images.githubusercontent.com/1629901/102390496-15e86f80-3f9a-11eb-8eea-0259bf0bb587.png">

The stack trace here is hard to understand, and not sure which atom is erroring here.  is there a way to have this reveal which line of code it is?

**Comment by dai-shi** [comment] 2020-12-16 22:51
Hi, thank for the suggestion. I noticed in some cases, it's not a bug but an expected behavior, so we need to make the text clearer. I'm not sure if we can show that stack trace.

Meanwhile, would you try two things?
- try the latest version (v0.12.0)
- add `debugLabel` on atoms. `const a = atom(...); a.debugLabel = 'foo'`

**Comment by Aslemammad** [comment] 2021-01-14 06:49
Unfortunately, there is not enough info about this issue, so I'm going to close it. Feel free to reopen.

**Closed by Aslemammad** 2021-01-14 06:49 UTC
Labels: needs info
