### ISSUE TITLE
atomWithToggleAndStorage not persisting in react-native

### ISSUE THREAD

**Issue by iamhaaamed** [pmndrs/jotai#1037] opened 2022-03-03 16:29 UTC
this is my atom:
```
import AsyncStorage from '@react-native-async-storage/async-storage';
import {createJSONStorage} from 'jotai/utils';

import {atomWithToggleAndStorage} from './atomWithToggleAndStorage';

const isOnboardingViewedAtom = atomWithToggleAndStorage(
  'isOnboardingViewed',
  false,
  {
    ...createJSONStorage(() => AsyncStorage),
    delayInit: true,
  },
);

export default isOnboardingViewedAtom;

```
and this is my usage:
```
export default function OnboardingScreen() {
  const [, setIsOnboardingViewed] = useAtom(isOnboardingViewedAtom);

  const onPressDone = () => {
    setIsOnboardingViewed(true);
  };

  return (
    <CustomContainer>
        <Button
          onPress={onPressDone}>
        </Button>
    </CustomContainer>
  );
}
```
the isOnboardingViewed value is changed after calling setIsOnboardingViewed, but when I refresh the screen the value reverted to it's default value(false).

**Comment by dai-shi** [comment] 2022-03-03 23:40
Thanks for reporting. Do you still see the issue with `atomWithStorage`? Would it be possible to create a minimal reproduction with expo snack?

**Comment by iamhaaamed** [comment] 2022-03-04 03:16
Yes, issue also exist with atomWithStorage.
Here is the snack reproduction:
[https://snack.expo.dev/ejgGDPFCX](https://snack.expo.dev/ejgGDPFCX)

**Comment by dai-shi** [comment] 2022-03-04 14:48
Hmmm, I can't reproduce it.

> but when I refresh the screen the value reverted to it's default value(false).

How do you refresh the screen?

**Comment by TwistedMinda** [comment] 2022-05-19 01:14
@dai-shi I can't reproduce either. I think the OP may have mis-read his logs. Because indeed, when you use `delayInit: true`, and you "refresh" the screen (he means reload the hot reloader / kill app + relaunch), the first log you will see is indeed the default value of your atom. But soon after, the promise from AsyncStorage resolves and the listening component is updated with the stored value.

Nothing to see here, we can close the issue.

**Closed** 2022-05-19 02:51 UTC
Labels: needs repro
