### ISSUE TITLE
Possible Bug: base atom used by derived atom is not mounted through Setter's get function

### ISSUE THREAD

**Issue by channeladam** [pmndrs/jotai#1063] opened 2022-03-18 14:28 UTC
Hi,

I think there might be a bug, or perhaps I am not doing something correctly?

I have an atom that is similar to the atomWithStorage atom, in that there is a base atom with onMount defined.

I have an Action Atom that is executed from the result of a useUpdateAtom().

Inside that Action Atom's Setter, when I use the get() to get the value of my atom that has onMount defined, the base atom is never mounted.

Roughly like this:
```
const myAtomWithMount = atomDerivedWithOnMountOnBaseAtom();

const actionCallback = useUpdateAtom(myActionAtom);
actionCallback();
 
const myActionAtom = atom(() => undefined, (get, set) => {
  const result = get(myAtomWithMount);
  // ^^^^^^^^ myAtomWithMount's base atom is never mounted
}); 
```

And this is the same when trying to access the atom through an atomFamily... which is the real use case I have for it.  I am trying to merge values into a number of child atoms in the family, and cannot do a useAtomValue() call on each - hence doing it in bulk in an Action Atom.

Any thoughts would be appreciated, thank you.

**Comment by dai-shi** [comment] 2022-03-18 22:52
Hi, thanks for using jotai.
The behavior is by design. onMount is effective when an atom is "used", and `get` in `write` function isn't considered as "used". (otherwise, as there's no way to unmount it, it leads to memory leaks.)

The easiest solution would be to "use" myAtomWithMount, with useAtom or `get` in `read` function.
Suppose it's not an option in this case, another solution would be to run logic in the `write` function. Something like the following:

```js
const baseAtom = atom(0)
const isMountedAtom = atom(false)
const actionAtom = atom(null, (get, set) => {
  // mount baseAtom
  if (!get(isMountedAtom)) {
    // do something, but we can't clean up automatically
    set(isMountedAtom, true)
  }
  // ...
})
```


#942 has a related discussion.

**Comment by channeladam** [comment] 2022-03-19 03:45
Hi, thanks for answering.

I was already investigating that type of approach.

So in simple terms, there are limitations with atoms like atomWithStorage which use onMount, such that the value cannot be retrieved from storage from within an Action Atom /  Setter using the Setter's `get` function unless the atom was already accessed via `useAtomValue` or `useAtom` (or any `get` in a Read function).

Thank you.

**Comment by dai-shi** [comment] 2022-03-21 02:19
Yeah, your concern is true in general.

For atomWithStorage, the initial value is read from the storage (unless `delayInit` is on) even before `onMount`, but the limitation remains for the following changes from the storage. To solve this specific case, we should not cache the atom value, if the atom is not yet mounted. Yeah, that sounds consistent and less error-prone. Let's investigate this approach.

**Comment by Aslemammad** [comment] 2022-03-31 03:46
@dai-shi How the investigation would be for this issue?

**Comment by dai-shi** [comment] 2022-03-31 09:19
The issue originally reported is resolved as `working as intended`.

But then, it reveals an issue with atomWithStorage specifically. So, let me close this and open a new one.

> To solve this specific case, we should not cache the atom value, if the atom is not yet mounted.

On second thought, this seems wrong. Unless we cache atom values, it leads to double invocation. So, it turns out it's the issue with atomWithStorage, not the core issue.

**Closed by dai-shi** 2022-03-31 09:19 UTC
