### ISSUE TITLE
TS 2742 error using atomFamily

### ISSUE THREAD

**Issue by gunters63** [pmndrs/jotai#1391] opened 2022-09-02 04:46 UTC
I have a minor problem in my MonoRepo using Jotai.

I am using ESM modules everywhere (with Node16 module resolution) and normally let Typescript infer return types. I am using Typescript 4.7.4.

Using atomFamily gives me a TS 2742 error:

![image](https://user-images.githubusercontent.com/90346/188060291-72ee3316-9d59-4e91-9fe9-2dffc195c32c.png)

I examined the export file utils.ts and atomFamily.ts and I think the problem is that the return type of atomFamily uses a interface AtomFamily that is not re-exported in utils.ts.

In fact, when I change the line
````
export { atomFamily } from './utils/atomFamily';
````
  to 
````
export { atomFamily, type AtomFamily } from './utils/atomFamily';
````

the error goes away.

I can make a PR if desired.

**Comment by dai-shi** [comment] 2022-09-02 05:48
Do you explicitly use `AtomFamily` type in your code? Or, is it something your compiler does?
(In general, I want to find a solution without modifying things on the lib end. Not re-exporting is rather intentional. We used to avoid exporting at all, actually.)

**Comment by gunters63** [comment] 2022-09-02 05:58
I don't use AtomFamily explicitly in my code.  

My complete code looks like this:

````
import { atomWithControllerStorageAndVersion } from '@enso/react-comm/controllerStorage';
import { atomFamily } from 'jotai/utils';

import {
  getDefaultConfiguration,
  StatisticConfigurationVersion,
} from '$/config/defaultStatisticConfiguration.js';

const statisticsAtom = atomFamily((statisticName: string) => {
  const defaults = getDefaultConfiguration(statisticName);
  const atomName = `ui-statistic-${statisticName}`;

  const oneAtom = atomWithControllerStorageAndVersion(
    atomName,
    StatisticConfigurationVersion,
    defaults,
  );
  oneAtom.debugLabel = atomName;

  return oneAtom;
});

export default statisticsAtom;
````

The error goes away when I do not export statisticsAtom.
I confess I don't really understand this Typescript error :) and under which circumstances exactly it occurs.
I can try to make a minimal reproduction.

**Comment by dai-shi** [comment] 2022-09-02 06:27
Do you have something like `"declaration": true` in tsconfig.json?

**Comment by gunters63** [comment] 2022-09-02 06:35
yes, I have.

All packages in the monorepo use the same Typescript configuration. The libraries use `"declaration": true` because they use the tsc compiler to emit .d.ts files. 

The web app itself (where above code resides) which uses the libraries strictly wouldn't need this setting, it uses `tsc --noEmit`  for type checking and uses ViteJs/Rollup for bundling.

**Comment by gunters63** [comment] 2022-09-02 06:41
My web app extended the common Typescript configuration already like this:

````
{
  "compilerOptions": {
    "baseUrl": "src",
    "noEmit": true,
    "paths": {
      "$/*": ["./*"]
    },
    "tsBuildInfoFile": ".tsbuildinfo",
    "types": ["vite/client"]
  },
  "extends": "@enso/tsconfig/react.json",
  "include": ["src", "vite.config.ts", "bundleSirv.cts", "convert-locale.ts", "convert-signals.ts"]
}
````

I added these lines to the compilerOpions part:
````
    "declaration": false,
    "declarationMap": false,
````

This made the error go away :).

I was wondering already why I got this error only in the editor, not when checking with `tsc --noEmit`.

Thanks, I think the issue can be closed.

**Comment by gunters63** [comment] 2022-09-02 06:42
This being said. I wonder if the issue probably resurfaces when someone builds a module using Jotai and tries to export something of type AtomFamily,

**Comment by dai-shi** [comment] 2022-09-02 08:37
Closing but I'm curious why declaration: true doesn't work.

Let me know if you or someone can make a small reproduction hopefully without monorepo.

**Comment by dai-shi** [comment] 2022-09-02 08:38
Actually, I can leave it open for a while.

**Comment by gunters63** [comment] 2022-09-04 04:33
> We used to avoid exporting at all, actually.

I am not sure about this. Some want to set `noImplicitReturns` to true in their tsconfig. How can they return a `atomFamily` result from a function?

**Comment by dai-shi** [comment] 2022-09-04 05:40
Just what they would expect to return.
```ts
type MyFamily = {
  (param: number): PrimitiveAtom<number>;
};

export function createMyFamily(): MyFamily {
  return atomFamily((param: number) => atom(param));
}
```
https://tsplay.dev/WKRXpm

This might be controversial, but this allows for them to notice when jotai changes something with atomFamily. If they use exported types, they don't notice changes with this function. (which should be one of the reasons for explicit return types.)

**Comment by gunters63** [comment] 2022-09-04 05:49
Yes, this would also make my initial error in the IDE go away even when `declaration: true` is active.

That makes sense, thanks for the explanation.

**Comment by dai-shi** [comment] 2022-09-05 04:50
https://github.com/pmndrs/jotai/issues/1391#issuecomment-1235230354

**Closed by dai-shi** 2022-09-05 04:50 UTC
