### ISSUE TITLE
get() inside an async atom used with loadable does not do a distinct

### ISSUE THREAD

**Issue by neckaros** [pmndrs/jotai#874] opened 2021-12-06 11:14 UTC
i have `libraryAtom` atom wathcing part of my url to get the current libraryId.
I have a second async atom, `tagsAtom` that depends of this previous atom to do a request with the libraryId.
When i change page `libraryAtom` get set to the exact same value (=== return true) so i do not expect `tagsAtom` to rerun but it does.

I tried to replicate in the demo sandbox. And indeed setting the same value will not cause a re-render, but it will cause to recompute the dependents.

https://codesandbox.io/s/jotai-demo-forked-2g4s4?file=/src/App.js
In this sandbox i have a button to force a set to a fixed value 'hello'
if you look in the console if you click multiple times no render will be done but 'doing uppercase' will happen everytime.

is it an expected behavior? 
if yes it forces me to keep track in global values of the previous value of libraryId and the result of my promise, compare previous libraryId and if identical return the saved result?

_by the way but not related: not sure why 'render' happens twice everytime value change? if you think it might be an issue i will open a new one_

**Comment by dai-shi** [comment] 2021-12-06 11:34
You are trying with a very old version of the library. (I know the demo is using it.)
This is with the latest one: https://codesandbox.io/s/jotai-demo-forked-ko9m9

> not sure why 'render' happens twice everytime value change? if you think it might be an issue i will open a new one

An extra re-render without commits is an expected behavior. Simply put, it's something to work better in concurrent rendering.

**Comment by neckaros** [comment] 2021-12-06 11:54
My bad you are right.
I update the dependency and this simplified exemple does not reproduce my issue. It seems to happen as soon as i use `loadable`
i _upgraded_ my sandbox and i'm able to reproduce my issue: https://codesandbox.io/s/jotai-demo-forked-2g4s4?file=/src/App.js

**Comment by dai-shi** [comment] 2021-12-06 12:06
Yeah, this is expected with the implementation of `loadable`.
This example may show how it's working: https://codesandbox.io/s/jotai-demo-forked-idt0v?file=/src/App.js

If you want to avoid rendering when only state changes, you could use `selectAtom`.

**Comment by neckaros** [comment] 2021-12-06 12:59
Thanks for your help, i will look into the loadable code.
The problem is not with the re-rendering but more with the re-fetching. I want to minimize fetch call.
More over the user will still loose the already loaded content. For example i edited my sandbox with and async sleep and the content for the fetched page is no longer available for the time of the sleep-fetch if i click the hello button

**Comment by dai-shi** [comment] 2021-12-06 13:30
> The problem is not with the re-rendering but more with the re-fetching. I want to minimize fetch call.

Oh, that was my misunderstanding. And, yes it looks like an issue in `loadable`. With Suspense, it won't re-fetch. I thought #857 did something wrong, but v1.4.5 behaves the same, so it's from the beginning. Not sure instantly if this is fixable or not.

**Comment by neckaros** [comment] 2021-12-06 15:53
you are right that we don't have the issue with Suspense, but unfortunately i can't use Suspense with NextJS yet.

I tried to understand what is causing the re-fetching (re execution of the async read) but so far I failed 😨

**Comment by Pinpickle** [comment] 2021-12-06 21:15
This appears to be due to atoms derived from async atoms, not just loadable atoms - so I think it's a core issue? It's odd that a derived atom causes the upstream dependency to recalculate. 

Reproduction: https://codesandbox.io/s/jotai-demo-forked-y58e3

**Comment by dai-shi** [comment] 2021-12-06 23:06
@Pinpickle Thanks for the repro! Oh, it seems a core bug...
I can even reproduce it without async: https://codesandbox.io/s/jotai-demo-forked-cucwg

**Comment by dai-shi** [comment] 2021-12-07 07:21
I filed #877 to track the core issue. This issue is to focus on `loadable`. We hope if we resolve #877, this is resolved.

**Comment by Thisen** [comment] 2021-12-07 22:12
@neckaros, can you try out the build in #878? I can't reproduce with that build.

**Comment by neckaros** [comment] 2021-12-15 17:38
sorry @Thisen i missed your message. Perfect this build fix the issue! thanks!!

**Comment by dai-shi** [comment] 2021-12-15 22:40
It's released as https://github.com/pmndrs/jotai/releases/tag/v1.4.7.

**Closed by dai-shi** 2021-12-15 22:40 UTC
