### ISSUE TITLE
Immutability of "withImmer" and "atomWithImmer" upon initialization

### ISSUE THREAD

**Issue by SteliosKornelakis** [pmndrs/jotai#1022] opened 2022-02-21 13:50 UTC
It appears that when you initialize atoms with immer like this: 
```
searchViewStateAtom.js
const searchParamPrimitiveAtom = atom(new SearchViewState())

export const searchParamsAtom1 = withImmer(searchParamPrimitiveAtom);
export const searchParamsAtom2 = atomWithImmer(searchParamPrimitiveAtom);
export const searchParamsAtom3 = atomWithImmer(null);
```
And then use them within a component

```
test.js
//import searchParamsAtom

const [atom1, setAtom1] = useAtom(searchParamsAtom)
atom1.name = "Works while it shouldn't?"
//If you set with "setAtom1(new xx)" and retyr
setTimeout => atom1.name = "Throws immutability as it should?" 

const [atom2, setAtom2] = useAtom(searchParamsAtom)
atom2.name = "Works while it shouldn't?"
//If you set with "setAtom2(new xx)" and retry
setTimeout =>atom2.name = "Throws immutability as it should?" // SetTimeout code ommited 

const [atom3, setAtom3] = useAtom(searchParamsAtom)
//atom3 is null thus 
setAtom3(xx)
//then 
setTimeout => atom3.name = "Throws immutability as it should?" //SetTimeout code ommited 
```

**Comment by dai-shi** [comment] 2022-02-22 01:26
> const [atom1, setAtom1] = useAtom(searchParamsAtom)
> atom1.name = "Works while it shouldn't?"

This has nothing to do with immer. It works, but usually we shouldn't do it.
`freezeAtom` is a util to prohibit it.

> //If you set with "setAtom1(new xx)" and retyr
> setTimeout => atom1.name = "Throws immutability as it should?"

Now, this is interesting. I guess this is because immer freezes the resulting object.
From my perspective, this is unexpected behavior. But, maybe it can't be helped...

If you `setAutoFreeze(false)`, the behavior is consistent, right?
I don't think there's anything we can do other than that...

**Comment by dai-shi** [comment] 2022-03-03 23:59
Closing as answered (although, it's not nice DX-wise).

**Closed by dai-shi** 2022-03-03 23:59 UTC

**Comment by SteliosKornelakis** [comment] 2022-03-07 23:11
Confirming by using `setAutoFreeze(false) ` behavior is consistent.
