### ISSUE TITLE
`useAtomCallback` creates a lot of atoms, resulting in performance issues

### ISSUE THREAD

**Issue by papermana** [pmndrs/jotai#641] opened 2021-08-07 11:23 UTC
`useAtomCallback` dynamically creates an atom whenever it is called, once per call site. Because of that, code with a number of components, where each component uses just a couple of callbacks, can result in a very large number of atoms being created. This appears to have a _serious_ impact on performance.

I made a recording where I show the extent of the problem (sorry for crappy quality, I had to compress it because it was too big for Github). I also have a link to the Codesandbox I used.

https://codesandbox.io/s/demonstration-of-useatomcallback-performance-issues-29qtj?file=/src/App.tsx.

https://user-images.githubusercontent.com/10849003/128598500-a75f8984-a1f9-4da0-8f6b-5e7dd4207c84.mov

**Comment by dai-shi** [comment] 2021-08-07 12:07
Thanks for reporting and reproduction!

It seems to me this is unavoidable and, for performance, we need to educate using dedicated write only atoms instead of useAtomCallback.

(I wonder if this is useAtomCallback specific, or just creating new atoms. Anyways, it would  be nice to improve if possible. Can anyone help?)

**Comment by papermana** [comment] 2021-08-07 12:28
Why does `useAtomCallback` create a new atom, though? It doesn't need to subscribe to changes, so it just requires access to functions that read the store or write to it, without any other extras. Or am I misunderstanding something?

If this is unavoidable, then to me, it would be best not to include this hook at all, and instead, users do need to be told to use write atoms.

**Comment by Thisen** [comment] 2021-08-07 18:39
Not sure I see the issue tbh - It's correct that `useAtomCallback` comes with a cost, because it's additional code. It's a way to interact with atoms imperatively.

@papermana, Can you just _not_ use it or lift the state up, so you have the `useAtomCallback` in the parent component?

**Comment by dai-shi** [comment] 2021-08-07 22:34
I just noticed something. Atom creation should be very lightweight, but useAtom comes with a cost. useUpdateAtom is provided for better performance. We have a ground rule that a util (like functions in `jotai/utils`) only depends on core (= `jotai`), but let's make an exception here. Will create a PR.

**Comment by dai-shi** [comment] 2021-08-07 22:46
https://ci.codesandbox.io/status/pmndrs/jotai/pr/644
@papermana Would you please use the build ☝️ and see if it improves the performance?

**Comment by papermana** [comment] 2021-08-09 18:36
@dai-shi This seems to have done the trick! I'm still seeing some performance issues in my own code, but I think that has to be unrelated. In the sandbox I created, there doesn't appear to be any degraded performance anymore.

@Thisen No offense, but that's kind of a strange reasoning. All code is additional code (it's in addition to having less code), that doesn't mean that it has to have poor performance. There are two problems with the existing implementation:
1. It's slow. Simply that — ideally, a library shouldn't have footguns.
2. It goes against the established pattern. I think everyone is used to `useCallback` by this point, and there's never been a need to lift that up to a context or something, because it just creates a function.

Anyway, it seems that the issue has been fixed, so it's not important anymore.

**Comment by Thisen** [comment] 2021-08-09 19:26
No offense taken, but the given scenario is a classic React issue, where lifting up state would solve the issue. 🙂

**Comment by dai-shi** [comment] 2021-08-09 22:41
@papermana Thanks for the confirmation. Will merge #644 later.
I knew useAtom is slower than useUpdateAtom, but not how slower.
My expectation was it's not very noticeable for moderate apps.
For benchmarking, we prefer useUpdateAtom as it's faster.
This issue is about useAtomCallback and will be fixed by #644.

Now, my little concern here is, as of now, useAtom is the core api we recommend using, and useUpdateAtom is to be used for performance critical situation.
So, ideally, it would be nice if we could improve the performance of useAtom.
Not sure how much room left, but there can be some.
To improve performance, benchmarking/measuring is important, which runs locally.
Would you help us revealing the cost of useAtom? @papermana 
I suspect internal `subscribeAtom` is slow, but not 100% sure.
If it is, we might be able to use `./benchmarks`.

**Closed** 2021-08-10 09:31 UTC

**Comment by papermana** [comment] 2021-08-10 23:55
@dai-shi I will try to investigate the cause of the slowness, but can't make any specific promises right now, because I'm fairly busy with stuff. 🙁 Thank you for your work on this library, it's very nice.
