### ISSUE TITLE
State resets with React Fast Refresh

### ISSUE THREAD

**Issue by alan-nf** [pmndrs/jotai#1150] opened 2022-05-10 21:55 UTC
Expected: when React Fast Refresh updates UI on save, jotai state should not be lost. E.g. a primitive counter atom like `const countAtom = atom(0)` should maintain it's value across fast refreshes.
Actual: all jotai global state resets when React Fast Refresh updates the UI.

Codesandbox: https://codesandbox.io/s/jotai-react-refresh-bug-807nez?file=/src/Jotai.tsx
Local demo: https://github.com/alan-nf/jotai-react-refresh-issue

Instructions:
1. Click the +1 button to increment the counter
2. Edit the text in the `Copy` component to say something else. The counter will be reset back to 0.

NOTE: related discussion about React Fast Refresh being broken in https://github.com/pmndrs/jotai/issues/1025. I cannot reproduce things being totally broken and I'm just seeing this reset issue.

**Comment by dai-shi** [comment] 2022-05-11 02:56
@Thisen Can you take a look?

**Comment by Thisen** [comment] 2022-05-11 08:47
I'll take a look!

**Comment by Thisen** [comment] 2022-05-11 09:30
@alan-nf, the Codesandbox doesn't seem to be using the `jotai/babel/plugin-react-refresh`. Am I blind? 😅

**Comment by alan-nf** [comment] 2022-05-11 18:24
No you're not blind, heh. It's using Create React App which uses react refresh under the covers

from https://javascript.plainenglish.io/react-fast-refresh-the-new-react-hot-reloader-652c6645548c:

> Starting from 4.x, Create React App enables React Fast Refresh by default. If your project is built off of Create React App, all you need to do is upgrade.

more specifically, it's using `@pmmmwh/react-refresh-webpack-plugin@^0.5.3`

This is where it's hooked up: https://github.com/facebook/create-react-app/blob/main/packages/react-scripts/config/webpack.config.js#L35

**Comment by alan-nf** [comment] 2022-05-11 18:29
And, if you grab [the demo that can run locally](https://github.com/alan-nf/jotai-react-refresh-issue), you can save a file edit and then see the network requests related to the react refresh update:

![image](https://user-images.githubusercontent.com/100322190/167920423-960d42b4-260e-46e7-b7e7-3971fe9ad860.png)

**Comment by alan-nf** [comment] 2022-05-11 18:32
I noticed that the hot update includes the atom declaration, presumably because it's in the same file as the component I'm editing. If I move that component to a separate file and edit it there, the jotai state stops resetting. That seems like totally reasonable behavior, and therefore isn't really reproducing the issue I'm seeing.

In my codebase, editing files that do not have the jotai atom declarations are still resulting in the reset, so I guess I'm hitting a different bug. I'll try to get a simple repro of that issue.

**Comment by alan-nf** [comment] 2022-05-11 19:02
Ugh, I can't reproduce with vite, even when I perfectly match the versions of all the packages in my codebase. Here it is working just fine: https://stackblitz.com/edit/vitejs-vite-2tuyjr?file=src/App.tsx

I'm going to try to figure out why this isn't working specifically in my codebase. I'll reopen this issue if I can get a correct repro of the problem.

**Comment by dai-shi** [comment] 2022-06-03 23:57
https://github.com/pmndrs/jotai/pull/1203#issuecomment-1146409731

@Thisen can you communicate with @alan-nf about this?

**Comment by Thisen** [comment] 2022-06-07 07:26
I'll look into this.

@alan-nf can you add an updated reproduction?

**Comment by alan-nf** [comment] 2022-06-13 02:55
Question: if I'm using vite and the `@vitejs/plugin-react` vite plugin, do I need anything else to get full react refresh support? Do I still need the `jotai/babel/plugin-react-refresh` babel plugin?

**Comment by Thisen** [comment] 2022-06-20 11:42
> fwiw I'm experiencing this issue as well w/ Vite 2.9.9, React 18, Jotai 1.7.2. Not sure if this is helpful, but here's a [repro](https://stackblitz.com/edit/vitejs-vite-qam2xp?file=src%2FApp.tsx&terminal=dev) on stackblitz.
> 
> steps to reproduce:
> 
> * click the `count is 0` button a few times
> * add some text to the document.

I'll look into `vite` support.

**Comment by Thisen** [comment] 2022-06-21 21:11
@bstro have you tried to configure `vite` to use the Jotai Babel preset?
https://github.com/vitejs/vite/tree/main/packages/plugin-react#babel-configuration

**Comment by bstro** [comment] 2022-06-22 17:20
@Thisen yes, I copied the setup from the [guide](https://jotai.org/docs/guides/vite) on my project and it has no effect.

I can't use it in the StackBlitz example—for some reason adding the jotai babel plugin triggers this compilation error: `[plugin:vite:react-babel] /home/projects/vitejs-vite-akwqmd/src/main.tsx: _babel_template.default is not a function
`

**Comment by bstro** [comment] 2022-06-26 21:03
@Thisen I attempted to get Vite configured with the jotai babel preset to recreate the state reset bug but I keep running into the above compilation error. Here's [a stackblitz link](https://stackblitz.com/edit/vitejs-vite-w1eq1w?file=src%2FApp.tsx,package.json,vite.config.ts&terminal=dev).

**Comment by bstro** [comment] 2022-06-26 21:23
Here's a [reproduction on stackblitz](https://stackblitz.com/edit/vitejs-vite-ghb1dr?file=src%2FApp.tsx,package.json) of the state reset issue.

In my project, I am using xstate and jotai's `atomWithMachine`.

the bug might be related to jotai's xstate support. I first tried to reproduce the bug without xstate. I can only recreate the bug after adding xstate and reimplementing the inc/dec counter with xstate. This may be unrelated to @alan-nf's original bug report, but a bug nonetheless.

I hope this is helpful!

**Comment by Thisen** [comment] 2022-06-27 08:07
> Here's a [reproduction on stackblitz](https://stackblitz.com/edit/vitejs-vite-ghb1dr?file=src%2FApp.tsx,vite.config.ts) of my state reset issue.
> 
> The bug I'm seeing might be related to jotai's xstate module rather than @alan-nf's original issue. So far, I have only been able to reproduce the bug when using `atomWithMachine`.
> 
> I hope this is helpful in some way.

I'm not sure how much I can do without a reproduction using only the core modules. @dai-shi, any ideas if we could have a problem with `xstate` module?

**Comment by Thisen** [comment] 2022-06-27 20:17
> Part of the problem is that we've all been discussing somewhat separate issues:
> 
> * In my real (Vite) project, I'm having two separate problems:
>   
>   * when files with atoms get HMR updated, my state gets reset. I don't know how to integrate `jotai/babel/plugin-react-refresh` with Vite so perhaps this is expected.
>   * Vite is always HMR updating my files with state and I don't know why as they aren't getting edited
> * @bstro is reproducing a react refresh bug with `atomWithMachine`
> 
> So put another way, the problems are:
> 
> 1. What goes into a Vite hmr update is hard to debug
> 2. It's not clear how to integrate Vite + Jotai in a way that enables react-refresh in files that have atoms in them
> 3. There might be other bugs, e.g. with `atomWithMachine`
> 
> If you want a simple repro, [here is one](https://stackblitz.com/edit/vitejs-vite-9jh1zw?file=src%2FApp.tsx). This repro:
> 
> 1. Uses Vite + Jotai (only `atom` / `useAtom`)
> 2. Has both the atom and UI in App.tsx. Updating App.tsx resets the counter.
> 3. `jotai/babel/plugin-react-refresh` is not configured. I don't know how to configure it with Vite
> 
> [This](https://stackblitz.com/edit/vitejs-vite-2tuyjr?file=src%2FApp.tsx,src%2Fstate.ts) is the same code but the atom is moved to a separate file which lessens the problem with refresh (editing App.tsx does NOT reset the state, but editing state.ts still does reset the state)

There's docs in Vite on how to configure `babel` plugins:
https://github.com/vitejs/vite/tree/main/packages/plugin-react#babel-configuration

Have you tried that?

**Comment by Thisen** [comment] 2022-06-27 21:08
> If I try to add the babel plugin [on stackblitz](https://stackblitz.com/edit/vitejs-vite-7ubsyk?file=vite.config.ts,src%2FApp.tsx):
> 
> ```ts
> export default defineConfig({
>   plugins: [
>     react({
>       babel: {
>         plugins: ['jotai/babel/plugin-react-refresh'],
>       },
>     }),
>   ],
> });
> ```
> 
> Error:
> 
> > _babel_template.default is not a function
> 
> Error Details
> If I try to do the same thing locally ([repo on github](https://github.com/alan-nf/jotai-vite-react-refresh)), I get the error:
> 
> > templateBuilder is not a function
> 
> Error Details

Duplicate of #1251.

**Comment by alan-nf** [comment] 2022-06-28 05:12
> Duplicate of #1251.

👍 I subscribed to that thread. When a fix is released I will see if there are any other blockers to getting Vite + Jotai + React Refresh playing nicely together and will report back here. Thanks!

**Comment by Thisen** [comment] 2022-06-30 06:11
@alan-nf This is solved in 1.7.3 :)

**Comment by alan-nf** [comment] 2022-06-30 06:13
@Thisen I saw. I proofed it in [the Stackblitz sandbox](https://stackblitz.com/edit/jotai-vite-react-refresh?file=src%2FApp.tsx) and it works perfectly there. I froze the sandbox and renamed it if you want to use it as an example/demo of vite + jotai working with react refresh.

I have a note to myself to verify that this fixes things in my actual work project. I will report back as soon as I verify that.

Thank you *so* much for fixing this. Should be a huge productivity booster.

**Comment by Thisen** [comment] 2022-06-30 06:26
Glad to hear that!

**Closed by Thisen** 2022-06-30 06:26 UTC

**Comment by dai-shi** [comment] 2022-06-30 13:58
> the atom update methods (result of `useUpdateAtom`) is a new function

Hm, not exactly sure, but if the atom reference is the same, the function should be the same. Can you create a minimal reproduction with codesandbox?

**Comment by alan-nf** [comment] 2022-07-01 19:08
> but if the atom reference is the same, the function should be the same. Can you create a minimal reproduction with codesandbox?

Is stackblitz okay? if so, here you go: https://stackblitz.com/edit/jotai-vite-react-refresh-fretjv?file=src%2FApp.tsx

Note that the atom reference is also changing as part of the hmr.

I don't think this is a bug. In the stackblitz repro I demonstrate that it happens with setState as well (both the state and updater are new references).

**Comment by dai-shi** [comment] 2022-07-02 01:44
Thanks.

> https://stackblitz.com/edit/jotai-vite-react-refresh-fretjv?file=src%2FApp.tsx

"The updateInlineCount function was updated 12 times"
"The inlineCountAtom atom was updated 12 times"
"The useState updater was updated 12 times"

Yeah, looks like working perfectly.
