### ISSUE TITLE
Suspense doesn't resume on derived atom with an async dependency resolving to the same value

### ISSUE THREAD

**Issue by citolen** [pmndrs/jotai#742] opened 2021-09-29 13:04 UTC
I'm facing an issue where Suspense doesn't resume when the async atom dependency of a derived atom resolves to the same value it had.

Here is a codesandbox highlighting the issue: https://codesandbox.io/s/kev5t?file=/src/App.tsx
By clicking on `fetch data`, Suspense will get stuck even though the underlying async atom has resolved.
The problem seems to occur when the atom resolves to the same value it had.

I'm not familiar enough with Jotai's code base to find the root cause, perhaps I'm declaring the derived atom incorrectly, but it seems to be inline with the documentation. (https://docs.pmnd.rs/jotai/basics/async)

**Comment by dai-shi** [comment] 2021-09-29 15:25
Hi, thanks for reporting.
This can be something we have faced several times and struggled to reproduce stably.

> The problem seems to occur when the atom resolves to the same value it had.

This is a very good finding. ( @aulneau do you think it's the same situation in #702?)

> I'm not familiar enough with Jotai's code base to find the root cause

The async part is a bit complicated. Let's create a failing test spec and then investigate deep.
Would you be willing to try modifying your reproduction to be minimal? Reduce code more and still reproduce the issue. It's already small enough to understand, but it may help to understand the issue by trying some patterns.

> perhaps I'm declaring the derived atom incorrectly, but it seems to be inline with the documentation.

Yeah, I hope it should work. Let me mark this as a bug for now.

**Comment by citolen** [comment] 2021-09-30 07:14
@dai-shi Here is a smaller example that also highlights that it works with the async atom, but not with the derived one: https://codesandbox.io/s/stoic-bhaskara-yd2fg?file=/src/App.tsx

Another thing I've noticed is that it seems to go into an infinite loop, after you've clicked on the button and the Suspense is stuck, I'm getting a Chrome Renderer at max CPU.

I've created a test spec that fails.
You will need to add `@testing-library/jest-dom`.
The last statement will fail.

```typescript
// tests/async.test.tsx
import '@testing-library/jest-dom'

// ...

it('does not show async stale result on derived atom', async () => {
  const committed: any[] = []
  const countAtom = atom(0)
  const asyncAlwaysNullAtom = atom(async (get) => {
    get(countAtom)
    await new Promise((r) => setTimeout(r, 10))
    return null
  })
  const derivedAtom = atom((get) => {
    const value = get(asyncAlwaysNullAtom)
    committed.push(value)
    return value
  })

  const DisplayDerivedValue = () => {
    const [derivedValue] = useAtom(derivedAtom)

    return <div>derived value:{derivedValue}</div>
  }

  const DisplayAsyncValue = () => {
    const [asyncValue] = useAtom(asyncAlwaysNullAtom)

    return <div>async value:{asyncValue}</div>
  }

  const Test = () => {
    const [count, setCount] = useAtom(countAtom)
    return (
      <div>
        <div>count: {count}</div>
        <Suspense fallback={<div>loading derived value</div>}>
          <DisplayDerivedValue />
        </Suspense>
        <Suspense fallback={<div>loading async value</div>}>
          <DisplayAsyncValue />
        </Suspense>
        <button onClick={() => setCount((c) => c + 1)}>button</button>
      </div>
    )
  }

  const { getByText, findByText } = render(
    <StrictMode>
      <Provider>
        <Test />
      </Provider>
    </StrictMode>
  )

  expect(await findByText('count: 0')).toBeVisible()
  await waitFor(() => expect(getByText('loading async value')).toBeVisible())
  await waitFor(() => expect(getByText('loading derived value')).toBeVisible())
  await waitFor(() => expect(getByText('async value:')).toBeVisible())
  await waitFor(() => expect(getByText('derived value:')).toBeVisible())
  expect(committed).toEqual([null])

  fireEvent.click(getByText('button'))

  expect(await findByText('count: 1')).toBeVisible()
  await waitFor(() => expect(getByText('loading async value')).toBeVisible())
  await waitFor(() => expect(getByText('loading derived value')).toBeVisible())
  await waitFor(() => expect(getByText('async value:')).toBeVisible())
  await waitFor(() => expect(getByText('derived value:')).toBeVisible())
})
```

**Comment by dai-shi** [comment] 2021-09-30 07:42
Nice! Let's start with this failing test. You want to create a PR for adding the test? Or, I can do it if you prefer.
btw, we use simple `await findByText('loading async value')` in our tests. do you think adding `toBeVisible()` is better? what are possible pitfalls?

also, I would like to have `committed.push(value)` in useEffect.

**Comment by citolen** [comment] 2021-09-30 08:23
>we use simple await findByText('loading async value') in our tests. do you think adding toBeVisible() is better? what are possible pitfalls?

I believe `findByText` won't be enough to test what we want, it will resolve if what you're looking for is present in the DOM, but it does not check if it's visible.
When `Suspense` is suspended it displays the fallback and sets `display: none` on the content, `findByText` resolves even though the content is hidden because it's still in the DOM which won't be enough to validate the bug has been fixed.

Another way to check would be to wait for the fallback element to disappear from the DOM, something along those lines would work:
`await waitForElementToBeRemoved(() => getByText('loading derived value'))`

I will create a PR.

**Comment by dai-shi** [comment] 2021-09-30 08:40
> sets `display: none` on the content

Oh, this explains it. Thanks! I guess this behavior is in future versions of React? anyway, I think we should fix all async related tests... Or, maybe everything.

> await waitForElementToBeRemoved(() => getByText('loading derived value'))

This looks cleaner. I wonder if we have something similar for "visible" one.

---

```js
  expect(await findByText('count: 1')).toBeVisible()
  await waitFor(() => expect(getByText('loading async value')).toBeVisible())
```
☝️ Why you have two patterns? Can the second one in the first form??

**Comment by citolen** [comment] 2021-09-30 09:24
>Why you have two patterns? Can the second one be in the first form??

Possibly, either way I've done it differently on the PR which I hope is clearer.

**Comment by Pinpickle** [comment] 2021-09-30 21:50
I just ran into this, made a reproduction sandbox and then found this issue 😅 

The linked PR also fixes my issue so that's great!

**Closed** 2021-09-30 23:21 UTC
Labels: bug

**Comment by Hunni-Devteam** [comment] 2022-06-19 17:02
I'm apologize to commenting on already resolved issue 🙏 

Can I assume it affects using update(type: 'refetch') method on AtomWithQuery,
when the same API response wrote on derived (the response state of query) atom?

**Comment by dai-shi** [comment] 2022-06-19 23:30
atomWithQuery from jotai/query might behave differently, because RQ can return a new response object. jotai checks its value with `===`.
